<a href="https://colab.research.google.com/github/ianujrathore/GenerativeAI-and-AgenticAI/blob/main/Assignment_01_IMDb_Dataset_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMDb Dataset - Week Long Pandas Assignment

Complete all questions during the week. Write your solutions below each question.

### Question 1
Load the IMDb dataset using Pandas.

In [ ]:
# Write your solution here
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Summer training 2026/DataSet 2026/imdb_data.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Question 2
Display the first 10 rows of the dataset.

In [ ]:
# Write your solution here
df.head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,1/15/04,84.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Set sail for Muppet mayhem!,Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391
9,10,NaN,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,tt0310281,en,A Mighty Wind,"In ""A Mighty Wind"", director Christopher Guest...",4.672036,...,4/16/03,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Back together for the first time, again.",A Mighty Wind,"[{'id': 11800, 'name': 'mockumentary'}, {'id':...","[{'cast_id': 24, 'character': 'Jonathan Steinb...","[{'credit_id': '52fe45609251416c750545b3', 'de...",18750246

### Question 3
Display the last 10 rows of the dataset.

In [ ]:
# Write your solution here
df.tail(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2990,2991,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0118663,en,B.A.P.S.,Can two clueless Georgia homegirls with big he...,1.560980,...,3/28/97,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,These Pretty Women... Are Clueless!,B.A.P.S.,"[{'id': 1437, 'name': 'burglar'}, {'id': 1946,...","[{'cast_id': 3, 'character': 'Nisi', 'credit_i...","[{'credit_id': '52fe477b9251416c7509af57', 'de...",7240837
2991,2992,"[{'id': 107469, 'name': 'Save The Last Dance C...",13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",NaN,tt0206275,en,Save the Last Dance,"A white midwestern girl moves to Chicago, wher...",4.794088,...,1/12/01,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Only Person You Need To Be Is Yourself.,Save the Last Dance,"[{'id': 4118, 'name': 'ballet dancer'}, {'id':...","[{'cast_id': 18, 'character': 'Sara Johnson', ...","[{'credit_id': '52fe4533c3a36847f80c1c6b', 'de...",91038276
2992,2993,NaN,1135654,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0015400,en,The Thief of Bagdad,A recalcitrant thief vies with a duplicitous M...,3.878515,...,3/18/24,149.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,"""Happiness Must Be Earned""",The Thief of Bagdad,"[{'id': 255, 'name': 'male nudity'}, {'id': 14...","[{'cast_id': 3, 'character': 'The Thief of Bag...","[{'credit_id': '52fe45bec3a368484e06c70b', 'de...",1213880
2993,2994,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,Viktor Navorski is a man without a country; hi...,14.092373,...,6/17/04,128.0,"[{'iso_639_1': 'bg', 'name': 'български език'}...",Released,Life is waiting.,The Terminal,"[{'id': 242, 'name': 'new york'}, {'id': 822, ...","[{'cast_id': 4, 'character': 'Viktor Navorski'...","[{'credit_id': '52fe4259c3a36847f8017699', 'de...",219417255
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,9/18/92,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just because you’re accepted doesn’t mean you ...,School Ties,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

### Question 4
Find the total number of rows and columns in the dataset.

In [ ]:
# Write your solution here
df.shape

(3000, 23)

### Question 5
Display all column names.

In [ ]:
# Write your solution here
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

### Question 6
Check the data types of all columns.

In [ ]:
# Write your solution here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

### Question 7
Find the total number of missing values in each column.

In [ ]:
# Write your solution here
df.isnull().sum()

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
runtime                     2
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
dtype: int64

### Question 8
Generate summary statistics using describe().

In [ ]:
# Write your solution here
df.describe()

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

### Question 1
Display rows 10 to 20 and columns 2 to 5 using iloc.

In [ ]:
# Write your solution here
df.iloc[10:21, 2:6]

,budget,genres,homepage,imdb_id
10,1000000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0075148
11,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0093857
12,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547
13,53000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0377471
14,102000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0181689
15,500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://skinningmovie.com/synopsis.htm,tt1129437
16,26000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",NaN,tt0421239
17,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt1700845
18,8000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt1487118
19,32000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0388482
20,80000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,tt0120738

### Question 2
Display the first 15 rows using iloc.

In [ ]:
# Write your solution here
df.iloc[:15]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,1/15/04,84.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Set sail for Muppet mayhem!,Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391
9,10,NaN,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,tt0310281,en,A Mighty Wind,"In ""A Mighty Wind"", director Christopher Guest...",4.672036,...,4/16/03,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Back together for the first time, again.",A Mighty Wind,"[{'id': 11800, 'name': 'mockumentary'}, {'id':...","[{'cast_id': 24, 'character': 'Jonathan Steinb...","[{'credit_id': '52fe45609251416c750545b3', 'de...",18750246
10,11,"[{'id': 1575, 'name': 'Rocky Collection', 'pos...",1000000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0075148,en,Rocky,"When world heavyweight boxing champion, Apollo...",14.774066,...,11/21/76,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His whole life was a million-to-one shot.,Rocky,"[{'id': 240, 'name': 'underdog'}, {'id': 276, ...","[{'cast_id': 16, 'character': 'Rocky Balboa', ...","[{'credit_id': '579948e9c3a36874e9007b0b', 'de...",117235147
11,12,"[{'id': 48190, 'name': 'Revenge of the Nerds C...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0093857,en,Revenge of the Nerds II: Nerds in Paradise,The members of the Lambda Lambda Lambda frater...,10.543750,...,7/10/87,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're Back!,Revenge of the Nerds II: Nerds in Paradise,"[{'id': 5801, 'name': 'nerd'}, {'id': 6876, 'n...","[{'cast_id': 2, 'character': 'Lewis Skolnick',...","[{'credit_id': '52fe46f49251416c750891e9', 'de...",22642033
12,13,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",20.726578,...,9/15/99,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Look closer.,American Beauty,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 6, 'character': 'Lester Burnham',...","[{'credit_id': '52fe420ec3a36847f80007c5', 'de...",356296601
13,14,"[{'id': 91698, 'name': 'Chili Palmer Collectio...",53000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0377471,en,Be Cool,"Disenchanted with the movie industry, Chili Pa...",13.314233,...,3/4/05,118.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone is looking for the next big hit,Be Cool,"[{'id': 3605, 'name': 'baseball bat'}, {'id': ...","[{'cast_id': 4, 'character': 'Chili Palmer', '...","[{'credit_id': '52fe43cbc3a36847f807039f', 'de...",95226116
14,15,NaN,102000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0181689,en,Minority Report,John Anderton is a top 'Precrime' cop in the l...,20.666063,...,6/20/02,145.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The system is perfect until it comes after you.,Minority Report,"[{'id': 476, 'name': 'self-fulfilling prophecy...","[{'cast_id': 5, 'character': 'Chief John Ander...","[{'credit_id': '52fe4223c3a36847f8006f3d', 'de...",358372926

### Question 3
Extract only the columns: title, budget, revenue using loc.

In [ ]:
# Write your solution here
df.loc[:, ['title','budget','revenue']]

                                         title    budget    revenue
0                       Hot Tub Time Machine 2  14000000   12314651
1     The Princess Diaries 2: Royal Engagement  40000000   95149435
2                                     Whiplash   3300000   13092000
3                                      Kahaani   1200000   16000000
4                                   Marine Boy         0    3923970
...                                        ...       ...        ...
2995                                   Chasers         0    1596687
2996                          We Are the Best!         0     180590
2997                   The Long Kiss Goodnight  65000000   89456761
2998                          Along Came Polly  42000000  171963386
2999                                 Abduction  35000000   82087155

[3000 rows x 3 columns]

### Question 4
Display only the title and runtime columns.

In [ ]:
# Write your solution here
df.loc[:,['title','runtime']]

                                         title  runtime
0                       Hot Tub Time Machine 2     93.0
1     The Princess Diaries 2: Royal Engagement    113.0
2                                     Whiplash    105.0
3                                      Kahaani    122.0
4                                   Marine Boy    118.0
...                                        ...      ...
2995                                   Chasers    102.0
2996                          We Are the Best!    102.0
2997                   The Long Kiss Goodnight    120.0
2998                          Along Came Polly     90.0
2999                                 Abduction    106.0

[3000 rows x 2 columns]

### Question 5
Extract the last 20 rows of the dataset.

In [ ]:
# Write your solution here
df.iloc[-20:]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2980,2981,NaN,300000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",https://www.facebook.com/Actionherobiju/,tt5320514,ml,ആക്ഷൻ ഹീറോ ബിജു,Biju is an honest policeman who fights the inj...,0.350207,...,2/4/16,144.0,"[{'iso_639_1': 'ml', 'name': ''}]",Released,A ride with a police officer,Action Hero Biju,"[{'id': 1252, 'name': 'suicide attempt'}, {'id...","[{'cast_id': 1, 'character': 'Sub-Inspector Bi...","[{'credit_id': '56b4d47f92514112b90045f6', 'de...",2500000
2981,2982,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt4158876,en,Other People,"David, a struggling comedy writer fresh off fr...",3.069108,...,9/9/16,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Other People,"[{'id': 234102, 'name': 'misfits'}]","[{'cast_id': 0, 'character': 'David', 'credit_...","[{'credit_id': '57d923309251415959005090', 'de...",93000
2982,2983,NaN,500000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt2063781,en,Smashed,Kate and Charlie like to have a good time. The...,4.893812,...,9/12/12,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Smashed,NaN,"[{'cast_id': 1001, 'character': 'Kate Hannah',...","[{'credit_id': '557455c1c3a3686b7d003df7', 'de...",376597
2983,2984,NaN,35000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0118623,en,Anna Karenina,Anna (Marceau) is a wife and mother who has an...,5.660835,...,4/4/97,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"In a world of power and privilege, one woman d...",Anna Karenina,NaN,"[{'cast_id': 1, 'character': 'Anna Karenina', ...","[{'credit_id': '52fe47cac3a36847f81484f7', 'de...",791830
2984,2985,"[{'id': 221111, 'name': 'S.W.A.T. Collection',...",80000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://www.sonypictures.com/homevideo/swat/,tt0257076,en,S.W.A.T.,Hondo Harrelson recruits Jim Street to join an...,13.334952,...,8/8/03,117.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,You're either S.W.A.T. or you're not.,S.W.A.T.,"[{'id': 2434, 'name': 'liberation'}, {'id': 35...","[{'cast_id': 25, 'character': ""Sgt. Dan 'Hondo...","[{'credit_id': '5379d4980e0a261431006f58', 'de...",116643346
2985,2986,NaN,37665000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",http://www.sonypictures.com/homevideo/freedoml...,tt0349467,en,Freedomland,A black police detective must solve a strange ...,5.388535,...,2/17/06,113.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Truth Is Hiding Where No One Dares To Look.,Freedomland,"[{'id': 577, 'name': 'black people'}, {'id': 5...","[{'cast_id': 13, 'character': 'Lorenzo Council...","[{'credit_id': '52fe4551c3a36847f80c76e7', 'de...",14655628
2986,2987,NaN,20000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0338325,en,Paparazzi,A rising Hollywood actor decides to take perso...,12.553403,...,9/3/04,84.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,One good shot deserves another.,Paparazzi,"[{'id': 10183, 'name': 'independent film'}]","[{'cast_id': 1, 'character': 'Bo Laramie', 'cr...","[{'credit_id': '5678044292514179dd008c37', 'de...",16605763
2987,2988,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",NaN,tt0096246,en,The Terror Within,Experiments in biological warfare have destroy...,1.292125,...,1/20/89,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It Wants To Get Out!,The Terror Within,"[{'id': 1299, 'name': 'monster'}, {'id': 1852,...","[{'cast_id': 4, 'character': 'Hal', 'credit_id...","[{'credit_id': '52fe45d9c3a368484e072511', 'de...",858591
2988,2989,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0301978,fa,ده,A visual social examination in the form of ten...,0.984515,...,5/20/02,94.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Ten,"[{'id': 1156, 'name': 'sister sister relations...","[{'cast_id': 2, 'character': 'Driver', 'credit...","[{'credit_id': '52fe460a9251416c7506b0a7', 'de...",105656
2989,2990,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,tt0206367,en,The Trumpet Of The Swan,The adventures of a young Trumpeter swan who c...,0.851599,...,5/11/01,75.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sometimes being different helps you to find yo...,The Trumpet Of The Swan,"[{'id': 6653, 'name': 'trumpet'}, {'id': 10407...","[{'cast_id': 1, 'character': 'Father', 'credit...","[{'credit_id': '58bc9d609251416084044b0e', 'de...",100202
2990,2991,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0118663,en,B.A.P.S.,Can two clueless Georgia homegirls with big he...,1.560980,...,3/28/97,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,These Pretty Women... Are Clueless!,B.A.P.S.,"[{'id': 1437, 'name': 'burglar'}, {'id': 1946,...","[{'cast_id': 3, 'character': 'Nisi', 'credit_i...","[{'credit_id': '52fe477b9251416c7509af57', 'de...",7240837
2991,2992,"[{'id': 107469, 'name': 'Save The Last Dance C...",13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",NaN,tt0206275,en,Save the Last Dance,"A white midwestern girl moves to Chicago, wher...",4.794088,...,1/12/01,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Only Person You Need To Be Is Yourself.,Save the Last Dance,"[{'id': 4118, 'name': 'ballet dancer'}, {'id':...","[{'cast_id': 18, 'character': 'Sara Johnson', ...","[{'credit_id': '52fe4533c3a36847f80c1c6b', 'de...",91038276
2992,2993,NaN,1135654,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0015400,en,The Thief of Bagdad,A recalcitrant thief vies with a duplicitous M...,3.878515,...,3/18/24,149.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,"""Happiness Must Be Earned""",The Thief of Bagdad,"[{'id': 255, 'name': 'male nudity'}, {'id': 14...","[{'cast_id': 3, 'character': 'The Thief of Bag...","[{'credit_id': '52fe45bec3a368484e06c70b', 'de...",1213880
2993,2994,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,Viktor Navorski is a man without a country; hi...,14.092373,...,6/17/04,128.0,"[{'iso_639_1': 'bg', 'name': 'български език'}...",Released,Life is waiting.,The Terminal,"[{'id': 242, 'name': 'new york'}, {'id': 822, ...","[{'cast_id': 4, 'character': 'Viktor Navorski'...","[{'credit_id': '52fe4259c3a36847f8017699', 'de...",219417255
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,9/18/92,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just because you’re accepted doesn’t mean you ...,School Ties,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

### Question 6
Display rows 50 to 100 with only title and popularity columns.

In [ ]:
# Write your solution here
df.loc[50:100, ['title','popularity']]

                                                title  popularity
50                                    Moscow, Belgium    1.572904
51                                     The Great Race    4.473327
52                      The Last Flight of Noah's Ark    1.012665
53                                          For Keeps    5.410839
54                                              Risen    8.759801
55                                         Son in Law    9.122718
56                                      Queen to Play    2.947980
57                                     Batman & Robin   17.038824
58                                Were The World Mine    1.882446
59                            All About the Benjamins    3.909079
60                                      Casino Royale   23.065078
61                                            Trapeze    1.801071
62                                             Fallen    6.381612
63   Friday the 13th Part VIII: Jason Takes Manhattan    7.743144
64                                           Nebraska   11.160699
65                                         Bloodsport    8.822276
66                                      Henry's Crime    5.145185
67                                     A Touch of Sin    6.303552
68                              To Kill a Mockingbird   14.284787
69              The Fast and the Furious: Tokyo Drift    2.238808
70                                         The Jacket   12.092096
71                             The Motorcycle Diaries    7.667491
72                                           Cry-Baby    8.290384
73                                        Czech Dream    0.919556
74                                Jackson County Jail    2.482536
75                                       Fright Night    9.665251
76                          Kandukondain Kandukondain    0.660663
77                                         Caddyshack   10.451986
78                                   Sharky's Machine    2.633399
79                                                 31    6.636625
80                                          Dark Blue    4.984080
81                                           Shopgirl    4.349046
82                                   The Skeleton Key   10.947957
83                                               2010    7.482865
84                                       Silent House   10.239941
85                                              Congo    7.260574
86                                  Kramer vs. Kramer    9.741644
87                                Rumble in the Bronx   12.314278
88                               The Zookeeper's Wife   13.655178
89                                          Sommersby    4.359884
90                                  Kill Bill: Vol. 1   25.261865
91                                    His Secret Life    3.831960
92                           The Horseman on the Roof    1.690768
93                                             Hunger   14.322814
94                                   Mulholland Drive   18.184056
95                  And Here's What's Happening to Me    0.181963
96                                    Sleepless Night    2.942355
97                                             Target    1.042112
98                             Tad, the Lost Explorer   11.003515
99                                             Colors    5.529808
100                                        Dark Angel    7.958502

### Question 1
Find all movies whose original language is English (en).

In [ ]:
# Write your solution here
df.loc[df['original_language'] == 'en']

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,9/18/92,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just because you’re accepted doesn’t mean you ...,School Ties,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

### Question 2
Find all movies whose original language is Hindi (hi).

In [ ]:
# Write your solution here
df.loc[df['original_language'] == 'hi']

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
213,214,NaN,6700000,"[{'id': 28, 'name': 'Action'}]",NaN,tt2077833,hi,राउडी राठौर,Low-life thief Shiva and top-cop Vikram Rathor...,1.312833,...,6/1/12,143.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Rowdy Rathore,"[{'id': 1721, 'name': 'fight'}, {'id': 8015, '...","[{'cast_id': 11, 'character': 'Shiva / Vikram ...","[{'credit_id': '52fe4a0bc3a36847f81b58a9', 'de...",31000000
371,372,NaN,13100000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",http://www.thankyouthefilm.com/,tt1720254,hi,Thank You,The film is about three husbands having affair...,1.417392,...,4/8/11,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Husbands will say sorry ... Wives will say tha...,Thank You,NaN,"[{'cast_id': 1, 'character': 'Kishen', 'credit...","[{'credit_id': '52fe4651c3a368484e08a13f', 'de...",4100000
401,402,NaN,3000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0319736,hi,The Legend of Bhagat Singh,The Legend of Bhagat Singh is a 2002 Indian hi...,0.904409,...,6/7/02,155.0,"[{'iso_639_1': 'pa', 'name': 'ਪੰਜਾਬੀ'}, {'iso_...",Released,NaN,The Legend of Bhagat Singh,NaN,"[{'cast_id': 12, 'character': 'Bhagat K. Singh...","[{'credit_id': '52fe44849251416c9101372f', 'de...",6000000
419,420,NaN,3750000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10769, '...",http://www.atithithefilm.com/,tt1578116,hi,Atithi Tum Kab Jaoge,Atithi Tum Kab Jaoge? is the story of Puneet a...,0.597058,...,2/26/10,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,"Dear Guest, When Will You Leave?",NaN,"[{'cast_id': 1, 'character': 'Puneet, Pappu', ...","[{'credit_id': '5647c0359251413ade004b4d', 'de...",5000000
481,482,NaN,10500000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.cc2c-thefilm.com/,tt1091229,hi,Chandni Chowk To China,"Based in Delhi's Chandni Chowk, orphaned Sidhu...",1.970481,...,1/16/09,149.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Chandni Chowk To China,"[{'id': 4344, 'name': 'musical'}, {'id': 10540...","[{'cast_id': 10, 'character': 'Sidhu', 'credit...","[{'credit_id': '52fe43d2c3a368484e00004d', 'de...",9400000
585,586,NaN,10400000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt5074352,hi,दंगल,Dangal is an extraordinary true story based on...,8.792104,...,12/23/16,161.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dangal,"[{'id': 5565, 'name': 'biography'}, {'id': 597...","[{'cast_id': 0, 'character': 'Mahavir Singh Ph...","[{'credit_id': '5714ef3f92514146c80003ea', 'de...",310000000
627,628,NaN,16000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",http://www.yashrajfilms.com/Movies/MovieIndivi...,tt3495026,hi,Fan,The story of a fan whose world completely revo...,5.127876,...,4/15/16,142.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,World's biggest superstar got the universe's b...,Fan,"[{'id': 1523, 'name': 'obsession'}, {'id': 981...","[{'cast_id': 1, 'character': 'Gaurav Chandna /...","[{'credit_id': '569bc0de9251415e7000003c', 'de...",29251596
671,672,NaN,6400000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.anjaanaanjaani.erosentertainment.com,tt1499201,hi,Anjaana Anjaani,Akash (Ranbir Kapoor) and Kiara (Priyanka Chop...,1.822940,...,9/24/10,151.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,All the greatest love stories...are between st...,Anjaana Anjaani,"[{'id': 1252, 'name': 'suicide attempt'}, {'id...","[{'cast_id': 2, 'character': 'Kiara', 'credit_...","[{'credit_id': '58a2fb2cc3a3682902007108', 'de...",5900000
695,696,NaN,1,"[{'id': 10749, 'name': 'Romance'}, {'id': 53, ...",NaN,tt0374271,hi,Tere Naam,"Lower Caste Radhey Mohan is a no good slacker,...",1.280455,...,8/15/03,132.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Unfortunately a true love story,Tere Naam,NaN,"[{'cast_id': 3, 'character': 'Radhe Mohan', 'c...","[{'credit_id': '52fe491ec3a36847f8189cfb', 'de...",2
771,772,NaN,9000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://kaminey.utvnet.com/,tt1274295,hi,Kaminey,Guddu and Charlie are identical twins born and...,2.089842,...,8/14/09,135.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,Thif monfoon. Difcover your mean fide.,Kaminey,"[{'id': 14636, 'name': 'india'}]","[{'cast_id': 1, 'character': 'Charlie / Guddu'...","[{'credit_id': '52fe43f4c3a368484e007b65', 'de...",18130000
840,841,NaN,10721568,"[{'id': 18, 'name': 'Drama'}]",https://www.facebook.com/foxstarhindi/,tt5286444,hi,नीरजा,Neerja is a portrayal on the life of the coura...,1.686250,...,2/19/16,122.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Fear Gave Her Courage,Neerja,"[{'id': 4245, 'name': 'hijacking'}, {'id': 967...","[{'cast_id': 0, 'character': 'Neerja Bhanot', ...","[{'credit_id': '5692588192514115bf001d11', 'de...",2978994
848,849,NaN,6400000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt2359810,hi,रान्झाना,A small-town boy needs to break through the cl...,1.856101,...,6/21/13,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Raanjhanaa,"[{'id': 10048, 'name': 'unrequited love'}, {'i...","[{'cast_id': 1, 'character': 'Kundan', 'credit...","[{'credit_id': '52fe4c799251416c910f611d', 'de...",18000000
970,971,NaN,4200000,"[{'id': 10749, 'name': 'Romance'}, {'id': 28, ...",NaN,tt3142232,hi,Heropanti,Rising from present India in the conflicting e...,2.031919,...,5/23/14,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Heropanti,NaN,"[{'cast_id': 1, 'character': 'Bablu', 'credit_...","[{'credit_id': '53baa148c3a3685eb4006e29', 'de...",10000000
1004,1005,NaN,1000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt2350496,hi,Dabba,A mistaken delivery in Mumbai's famously effic...,10.766409,...,9/19/13,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Lunchbox,NaN,"[{'cast_id': 2, 'character': 'Saajan Fernandes...","[{'credit_id': '5476f65b9251415d7a0016eb', 'de...",4235151
1491,1492,NaN,5500000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt3767372,hi,Piku,"A road trip to Kolkata brings Piku, an archite...",2.942711,...,5/8/15,123.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Motion Se Hi Emotion,Piku,NaN,"[{'cast_id': 0, 'character': 'Bashkor Banerjee...","[{'credit_id': '5551de509251416a93005e01', 'de...",22159216
1572,1573,NaN,9100000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.rememberghajini.com/,tt1166100,hi,Ghajini,Sanjay a rich tycoon suffering from short term...,4.239080,...,12/25/08,183.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Ghajini,"[{'id': 331, 'name': 'tattoo'}, {'id': 154785,...","[{'cast_id': 12, 'character': 'Sanjay Singhani...","[{'credit_id': '52fe45c99251416c75062659', 'de...",76000000
1640,1641,NaN,4600000,"[{'id': 36, 'name': 'History'}, {'id': 28, 'na...",NaN,tt2356180,hi,Bhaag Milkha Bhaag,"The true story of the ""Flying Sikh"" world cham...",4.342418,...,7/12/13,186.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Now you will see his Real Story.,Bhaag Milkha Bhaag,"[{'id': 795, 'name': 'running'}, {'id': 1721, ...","[{'cast_id': 1, 'character': 'Milkha Singh', '...","[{'credit_id': '52fe4d1ac3a368484e1d74af', 'de...",25000000
1656,1657,NaN,18000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",http://www.chennaiexp2013.com/chennaiexpress.aspx,tt2112124,hi,Chennai Express,Rahul embarks on a journey to a small town in ...,4.193560,...,8/9/13,141.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,Ready... Steady... Po!,Chennai Express,"[{'id': 4412, 'name': 'grandfather'}, {'id': 4...","[{'cast_id': 2, 'character': 'Rahul Mithaiwala...","[{'credit_id': '581e56659251410f4f00f125', 'de...",62000000
1694,1695,NaN,521873,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,tt5662932,hi,रमन राघव २.०,Set in present day Mumbai the story follows th...,1.668794,...,6/24/16,127.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Raman Raghav 2.0,"[{'id': 10024, 'name': 'psychopathic killer'},...","[{'cast_id': 6, 'character': 'Ramanna (Raman)'...","[{'credit_id': '57160f17c3a3682f450033eb', 'de...",1013926
1719,1720,NaN,4437508,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://www.utvgroup.com/motion-pictures/coming...,tt2082197,hi,Barfi!,He is cute. He's shrewd. The girls love him. T...,3.779077,...,9/14/12,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Barfi,"[{'id': 1646, 'name': 'autism'}]","[{'cast_id': 5, 'character': 'Jhilmil Singh', ...","[{'credit_id': '5926294cc3a36877fd014ce9', 'de...",2804874
1729,1730,NaN,5200000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0164538,hi,दिल से,The clash between love and ideology is portray...,1.891138,...,8/22/98,163.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Dil Se..,"[{'id': 258, 'name': 'bomb'}, {'id': 321, 'nam...","[{'cast_id': 2, 'character': 'Amarkanth Varma'...","[{'credit_id': '57b53e789251410918000155', 'de...",13000000
1732,1733,"[{'id': 419784, 'name': 'Masti Collection', 'p...",5500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt2476154,hi,Grand Masti,"Amar, Prem and Meet are longtime friends who h...",1.250293,...,9/13/13,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,The Masti Boys are Back,Grand Masti,NaN,"[{'cast_id': 2, 'character': 'Amar', 'credit_i...","[{'credit_id': '52fe4db49251416c7513dd27', 'de...",47000000
1766,1767,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt0290326,hi,Tum Bin,"Shekhar, a businessman, accidentally kills his...",0.371679,...,7/13/01,158.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Love Will Find the Way,Tum Bin,"[{'id': 128, 'name': 'love triangle'}, {'id': ...","[{'cast_id': 1, 'character': 'Shekhar Malhotra...","[{'credit_id': '52fe46efc3a368484e0abfaf', 'de...",1486992
1948,1949,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0476805,hi,मालामाल वीकली,Lilaram sells lottery tickets and one customer...,1.479018,...,3/10/06,138.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Malamaal Weekly,NaN,"[{'cast_id': 1, 'character': 'Kanhaiya', 'cred...","[{'credit_id': '592dd1fbc3a36808c3000dd9', 'de...",204
1987,1988,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0347304,hi,कल हो ना हो,Naina is a very serious girl with a very serio...,5.584308,...,11/27/03,186.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Kal Ho Naa Ho,"[{'id': 242, 'name': 'new york'}, {'id': 958, ...","[{'cast_id': 8, 'character': 'Aman Mathur', 'c...","[{'credit_id': '52fe43b6c3a36847f8069c57', 'de...",13200241
1989,1990,"[{'id': 20970, 'name': 'Sarkar Collection', 'p...",1900000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0432047,hi,Sarkar,"The authority of a man, who runs a parallel go...",2.004745,...,7/1/05,123.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Sarkar,"[{'id': 417, 'name': 'corruption'}, {'id': 607...","[{'cast_id': 1, 'character': 'Subhash Nagre (S...","[{'credit_id': '576bae81c3a36864910013fc', 'de...",5900000
2239,2240,"[{'id': 44976, 'name': 'Dhoom Series', 'poster...",19500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt1833673,hi,धूम ३,"To avenge his father's death, a circus enterta...",5.326716,...,12/18/13,172.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dhoom 3,"[{'id': 291, 'name': 'circus'}, {'id': 2492, '...","[{'cast_id': 2, 'character': 'Sahir', 'credit_...","[{'credit_id': '59488707c3a36816c504b523', 'de...",91000000
2251,2252,NaN,130,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt1729637,hi,Bodyguard,Lovely Singh (Salman Khan) is the bodyguard of...,2.402032,...,8/31/11,130.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Bodyguard,"[{'id': 2251, 'name': 'lie'}, {'id': 2913, 'na...","[{'cast_id': 1, 'character': 'Lovely B. Singh'...","[{'credit_id': '52fe48a1c3a368484e102d25', 'de...",8
2287,2288,NaN,18000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt2979920,hi,बॉम्बे वेलवेट,"An ordinary man, who goes against all odds to ...",1.377993,...,5/15/15,151.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Bombay Velvet,"[{'id': 1416, 'name': 'jazz'}, {'id': 2792, 'n...","[{'cast_id': 1, 'character': 'Rosie', 'credit_...","[{'credit_id': '57d00957c3a36866a400269f', 'de...",1500000
2353,2354,NaN,8376800,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jodhaaakbar.com/,tt0449994,hi,Jodhaa Akbar,Jodhaa Akbar is a sixteenth century love story...,12.237488,...,2/15/08,213.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Jodhaa Akbar,"[{'id': 1157, 'name': 'wife husband relationsh...","[{'cast_id': 1, 'character': 'Jalaluddin Moham...","[{'credit_id': '52fe45c99251416c75062761', 'de...",13000000
2390,2391,NaN,7500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.khattameethathefilm.com/,tt1455811,hi,Khatta Meetha,"Struggling road construction contractor, Sachi...",0.494047,...,7/23/10,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Khatta Meetha,"[{'id': 235064, 'name': 'remake of malayalam f...","[{'cast_id': 4, 'character': 'Sachin Tichkule'...","[{'credit_id': '52fe468fc3a36847f8105a21', 'de...",10000000
2436,2437,NaN,4300000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt5946128,hi,Dear Zindagi,An unconventional thinker (Shah Rukh Khan) hel...,3.699552,...,11/24/16,149.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dear Zindagi,NaN,"[{'cast_id': 8, 'character': 'Kaira', 'credit_...","[{'credit_id': '57c6e9c3c3a3680ba4001c63', 'de...",3376375
2480,2481,NaN,6400000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt2168910,hi,Cocktail,"Gautam is an incorrigible flirt, who runs afte...",7.950488,...,7/13/12,144.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Sometimes good friends may be too good to shar...,Cocktail,"[{'id': 6054, 'name': 'friendship'}, {'id': 97...","[{'cast_id': 7, 'character': 'Veronica Malaney...","[{'credit_id': '52fe4bc8c3a36847f8213af9', 'de...",18800000
2538,2539,NaN,6900000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt0151150,hi,Josh,Shah Rukh Khan and Sharad Kapoor are the leade...,4.031500,...,6/9/00,162.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Josh,NaN,"[{'cast_id': 1, 'character': 'Max', 'credit_id...","[{'credit_id': '52fe4b82c3a368484e18c7f1', 'de...",15000000
2563,2564,NaN,7400000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0449999,hi,कभी अलविदा ना कहना,Dev and Maya are both married to different peo...,2.372520,...,8/11/06,193.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Love.... That Broke All Relationships,Kabhi Alvida Naa Kehna,"[{'id': 596, 'name': 'adultery'}, {'id': 34094...","[{'cast_id': 1, 'character': 'Dev Saran', 'cre...","[{'credit_id': '52fe45ee9251416c75067637', 'de...",17000000
2567,2568,NaN,11000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt2424988,hi,Gabbar Is Back,A vigilante network taking out corrupt officia...,1.812728,...,5/1/15,128.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Gabbar Is Back,NaN,"[{'cast_id': 1, 'character': 'Professor Aditya...","[{'credit_id': '5792ff149251410d12008917', 'de...",41000000
2807,2808,NaN,5300000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0439662,hi,Fanaa,Zooni Ali Beg (Kajol) is a blind Kashmiri girl...,3.003526,...,5/26/06,168.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,Destroyed in love...,Fanaa,"[{'id': 1741, 'name': 'blindness and impaired ...","[{'cast_id': 4, 'character': 'Zooni Ali Beg', ...","[{'credit_id': '52fe44aac3a36847f80a3315', 'de...",22175908
2828,2829,NaN,19500000,"[{'id': 10752, 'name': 'War'}, {'id': 36, 'nam...",NaN,tt3735246,hi,Bajirao Mastani,A historical account of the romance between th...,4.683689,...,12/18/15,150.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Bajirao Mastani,"[{'id': 232174, 'name': '–ª—é–±–æ–≤—å'}, {'id'...","[{'cast_id': 1, 'character': 'Baji Rao I', 'cr...","[{'credit_id': '560b66e0c3a3686814004c7d', 'de...",56000000
2857,2858,NaN,5400000,"[{'id': 53, 'name': 'Thriller'}]",NaN,tt2855648,hi,Madras Cafe,An Indian Intelligence agent journeys into a w...,2.399890,...,8/23/13,130.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Intercept the truth,Madras Cafe,"[{'id': 1990, 'name': 'cupboard'}, {'id': 5299...","[{'cast_id': 2, 'character': 'Vikram Singh', '...","[{'credit_id': '52fe4e08c3a368484e20a8ed', 'de...",6500000
2859,2860,"[{'id': 286951, 'name': 'Singham Collection', ...",3062000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt1948150,hi,Singham,A Bollywood classic directed by Rodit Shetty. ...,2.077410,...,7/22/11,143.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Singham,"[{'id': 1721, 'name': 'fight'}, {'id': 13116, ...","[{'cast_id': 1, 'character': 'Bajirao Singham'...","[{'credit_id': '52fe4802c3a368484e0e513f', 'de...",25034000
2959,2960,NaN,2300000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1093370,hi,Jab We Met,"Depressed after the passing of his father, Dha...",3.959411,...,10/26/07,145.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Jab We Met,"[{'id': 2038, 'name': ""love of one's life""}, {...","[{'cast_id': 9, 'character': 'Aditya Kashyap',...","[{'credit_id': '537ef0d8c3a36805a1002844', 'de...",4600000

### Question 3
Display only the title and original_language columns for Hindi movies.

In [ ]:
# Write your solution here
df.loc[df['original_language'] == 'hi',['title','original_language']]

                                 title original_language
3                              Kahaani                hi
213                      Rowdy Rathore                hi
371                          Thank You                hi
401         The Legend of Bhagat Singh                hi
419   Dear Guest, When Will You Leave?                hi
481             Chandni Chowk To China                hi
585                             Dangal                hi
627                                Fan                hi
671                    Anjaana Anjaani                hi
695                          Tere Naam                hi
771                            Kaminey                hi
840                             Neerja                hi
848                         Raanjhanaa                hi
970                          Heropanti                hi
1004                      The Lunchbox                hi
1491                              Piku                hi
1572                           Ghajini                hi
1640                Bhaag Milkha Bhaag                hi
1656                   Chennai Express                hi
1694                  Raman Raghav 2.0                hi
1719                             Barfi                hi
1729                          Dil Se..                hi
1732                       Grand Masti                hi
1766                           Tum Bin                hi
1948                   Malamaal Weekly                hi
1987                     Kal Ho Naa Ho                hi
1989                            Sarkar                hi
2239                           Dhoom 3                hi
2251                         Bodyguard                hi
2287                     Bombay Velvet                hi
2353                      Jodhaa Akbar                hi
2390                     Khatta Meetha                hi
2436                      Dear Zindagi                hi
2480                          Cocktail                hi
2538                              Josh                hi
2563            Kabhi Alvida Naa Kehna                hi
2567                    Gabbar Is Back                hi
2807                             Fanaa                hi
2828                   Bajirao Mastani                hi
2857                       Madras Cafe                hi
2859                           Singham                hi
2959                        Jab We Met                hi

### Question 4
Find movies having a budget greater than 100 million.

In [ ]:
# Write your solution here
df.loc[df['budget'] > 100000000]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
14,15,NaN,102000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0181689,en,Minority Report,John Anderton is a top 'Precrime' cop in the l...,20.666063,...,6/20/02,145.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The system is perfect until it comes after you.,Minority Report,"[{'id': 476, 'name': 'self-fulfilling prophecy...","[{'cast_id': 5, 'character': 'Chief John Ander...","[{'credit_id': '52fe4223c3a36847f8006f3d', 'de...",358372926
34,35,"[{'id': 90863, 'name': 'Rush Hour Collection',...",140000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0293564,en,Rush Hour 3,After an attempted assassination on Ambassador...,9.718111,...,8/8/07,91.0,"[{'iso_639_1': 'la', 'name': 'Latin'}, {'iso_6...",Released,The Rush Is On!,Rush Hour 3,"[{'id': 1704, 'name': 'ambassador'}]","[{'cast_id': 2, 'character': 'Det. James Carte...","[{'credit_id': '52fe43fac3a36847f807b5bd', 'de...",258022233
57,58,"[{'id': 120794, 'name': 'Batman Collection', '...",125000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt0118688,en,Batman & Robin,Along with crime-fighting partner Robin and ne...,17.038824,...,6/20/97,125.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Strength. Courage. Honor. And loyalty.,Batman & Robin,"[{'id': 848, 'name': 'double life'}, {'id': 84...","[{'cast_id': 4, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '59b66a169251417cbc011ec4', 'de...",238207122
60,61,"[{'id': 645, 'name': 'James Bond Collection', ...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/#/our-titles/233/Casino-Roy...,tt0381061,en,Casino Royale,"Le Chiffre, a banker to the world's terrorists...",23.065078,...,11/14/06,144.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone has a past. Every legend has a beginn...,Casino Royale,"[{'id': 131, 'name': 'italy'}, {'id': 383, 'na...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '53ac1fd7c3a3684bc8001908', 'de...",599045960
121,122,"[{'id': 106768, 'name': 'Tarzan (Animation) Co...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",http://disneydvd.disney.go.com/tarzanr-special...,tt0120855,en,Tarzan,Tarzan was a small orphan who was raised by an...,12.453452,...,6/18/99,88.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An immortal legend. As you've only imagined.,Tarzan,"[{'id': 690, 'name': 'gorilla'}, {'id': 1009, ...","[{'cast_id': 9, 'character': 'Tarzan', 'credit...","[{'credit_id': '5912c9a19251414e8005140a', 'de...",448000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2866,2867,"[{'id': 52984, 'name': 'National Treasure Coll...",130000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://disney.go.com/disneypictures/nationaltr...,tt0465234,en,National Treasure: Book of Secrets,Benjamin Franklin Gates and Dr. Abigail Chase ...,12.854373,...,12/13/07,124.0,"[{'iso_639_1': 'la', 'name': 'Latin'}, {'iso_6...",Released,The Greatest Adventure History Has Ever Revealed,National Treasure: Book of Secrets,"[{'id': 90, 'name': 'paris'}, {'id': 212, 'nam...","[{'cast_id': 1, 'character': 'Benjamin Frankli...","[{'credit_id': '52fe4460c3a36847f8092639', 'de...",457363168
2880,2881,NaN,150000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt2334879,en,White House Down,Capitol Policeman John Cale has just been deni...,9.920223,...,6/27/13,131.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It will start like any other day.,White House Down,"[{'id': 840, 'name': 'usa president'}, {'id': ...","[{'cast_id': 9, 'character': 'Cale', 'credit_i...","[{'credit_id': '52fe4baec3a36847f820f3b1', 'de...",205366737
2899,2900,NaN,127500000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,tt0130623,en,Dinosaur,An orphaned dinosaur raised by lemurs joins an...,9.998415,...,5/19/00,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,You have never seen anything like this.,Dinosaur,"[{'id': 843, 'name': 'cataclysm'}, {'id': 1423...","[{'cast_id': 1, 'character': 'Aladar (voice)',...","[{'credit_id': '52fe43899251416c75014337', 'de...",354248063
2927,2928,"[{'id': 645, 'name': 'James Bond Collection', ...",140000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/232/Die-Another-...,tt0246460,en,Die Another Day,Bond takes on a North Korean leader who underg...,12.996474,...,11/17/02,133.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,He’s never been cooler.,Die Another Day,"[{'id': 3290, 'name': 'laser'}, {'id': 156095,...","[{'cast_id': 20, 'character': 'James Bond', 'c...","[{'credit_id': '52fe45ff9251416c91045a7f', 'de...",431971116
2938,2939,"[{'id': 135416, 'name': 'Prometheus Collection...",130000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://www.projectprometheus.com/,tt1446714,en,Prometheus,A team of explorers discover a clue to the ori...,16.624854,...,5/30/12,124.0,"[{'iso_639_1': 'gd', 'name': ''}, {'iso_639_1'...",Released,The Search for Our Beginning Could Lead to Our...,Prometheus,"[{'id': 803, 'name': 'android'}, {'id': 4565, ...","[{'cast_id': 5, 'character': 'Dr. Elizabeth Sh...","[{'credit_id': '52fe481dc3a368484e0e9db7', 'de...",403170142

### Question 5
Find movies with revenue greater than 500 million.

In [ ]:
# Write your solution here
df.loc[df['revenue'] > 500000000]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
46,47,"[{'id': 8354, 'name': 'Ice Age Collection', 'p...",80000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://www.iceagemovies.com/films/ice-age-the-...,tt0438097,en,Ice Age: The Meltdown,"Diego, Manny and Sid return in this sequel to ...",16.646029,...,3/23/06,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Ice age is melting away.,Ice Age: The Meltdown,"[{'id': 2078, 'name': 'mammoth'}, {'id': 2079,...","[{'cast_id': 1, 'character': 'Manny (voice)', ...","[{'credit_id': '52fe4292c3a36847f80292c9', 'de...",660940780
60,61,"[{'id': 645, 'name': 'James Bond Collection', ...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/#/our-titles/233/Casino-Roy...,tt0381061,en,Casino Royale,"Le Chiffre, a banker to the world's terrorists...",23.065078,...,11/14/06,144.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone has a past. Every legend has a beginn...,Casino Royale,"[{'id': 131, 'name': 'italy'}, {'id': 383, 'na...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '53ac1fd7c3a3684bc8001908', 'de...",599045960
114,115,"[{'id': 119, 'name': 'The Lord of the Rings Co...",93000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.lordoftherings.net/,tt0120737,en,The Lord of the Rings: The Fellowship of the Ring,"Young hobbit Frodo Baggins, after inheriting a...",32.070725,...,12/18/01,178.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One ring to rule them all,The Lord of the Rings: The Fellowship of the Ring,"[{'id': 603, 'name': 'elves'}, {'id': 604, 'na...","[{'cast_id': 28, 'character': 'Frodo Baggins',...","[{'credit_id': '52fe421ac3a36847f80043ef', 'de...",871368364
188,189,NaN,180000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://disney.go.com/disneypictures/wall-e/,tt0910970,en,WALL·E,WALL·E is the last robot left on an Earth that...,16.088366,...,6/22/08,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An adventure beyond the ordinar-E.,WALL·E,"[{'id': 9799, 'name': 'romantic comedy'}]","[{'cast_id': 12, 'character': 'WALL¬∑E / M-O (...","[{'credit_id': '52fe43a29251416c75018101', 'de...",521311860
203,204,NaN,75000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://www.simpsonsmovie.com/,tt0462538,en,The Simpsons Movie,After Homer accidentally pollutes the town's w...,14.302911,...,7/25/07,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,See our family. And feel better about yours.,The Simpsons Movie,"[{'id': 494, 'name': 'father son relationship'...","[{'cast_id': 2, 'character': ""Homer / Itchy / ...","[{'credit_id': '52fe4211c3a36847f8001521', 'de...",527068851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2647,2648,"[{'id': 87359, 'name': 'Mission: Impossible Co...",145000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://www.missionimpossible.com/,tt1229238,en,Mission: Impossible - Ghost Protocol,In the 4th installment of the Mission Impossib...,14.258430,...,12/7/11,133.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No Plan. No Backup. No Choice.,Mission: Impossible - Ghost Protocol,"[{'id': 1721, 'name': 'fight'}, {'id': 9663, '...","[{'cast_id': 5, 'character': 'Ethan Hunt', 'cr...","[{'credit_id': '53563fb00e0a262861002dd0', 'de...",694713380
2737,2738,"[{'id': 645, 'name': 'James Bond Collection', ...",245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.sonypictures.com/movies/spectre/,tt2379713,en,Spectre,A cryptic message from Bond‚Äôs past sends him...,24.926577,...,10/26/15,148.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,A Plan No One Escapes,Spectre,"[{'id': 470, 'name': 'spy'}, {'id': 818, 'name...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '5751eed59251416b60000637', 'de...",880674609
2739,2740,"[{'id': 468222, 'name': 'The Incredibles Colle...",92000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://disney.go.com/disneyvideos/animatedfilm...,tt0317705,en,The Incredibles,Bob Parr has given up his superhero days to lo...,22.220214,...,11/5/04,115.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,"No gut, no glory",The Incredibles,"[{'id': 1308, 'name': 'secret identity'}, {'id...","[{'cast_id': 1, 'character': 'Bob Parr / Mr. I...","[{'credit_id': '52fe4531c3a36847f80c159d', 'de...",631442092
2770,2771,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,...,4/22/15,141.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A New Age Has Come.,Avengers: Age of Ultron,"[{'id': 8828, 'name': 'marvel comic'}, {'id': ...","[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694
2802,2803,"[{'id': 1241, 'name': 'Harry Potter Collection...",100000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,tt0295297,en,Harry Potter and the Chamber of Secrets,"Ignoring threats to his life, Harry returns to...",29.741452,...,11/13/02,161.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Hogwarts is back in session.,Harry Potter and the Chamber of Secrets,"[{'id': 391, 'name': 'flying car'}, {'id': 616...","[{'cast_id': 23, 'character': 'Harry Potter', ...","[{'credit_id': '52fe4267c3a36847f801bf67', 'de...",876688482

### Question 6
Find movies whose runtime is greater than 150 minutes.

In [ ]:
# Write your solution here
df.loc[df['runtime'] > 150]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
47,48,NaN,44000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",http://thehatefuleight.com/,tt3460252,en,The Hateful Eight,Bounty hunters seek shelter from a raging bliz...,20.328822,...,12/25/15,167.0,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,No one comes up here without a damn good reason.,The Hateful Eight,"[{'id': 801, 'name': 'bounty hunter'}, {'id': ...","[{'cast_id': 22, 'character': 'Major Marquis W...","[{'credit_id': '538aa95ec3a368714e0005b3', 'de...",155760117
51,52,NaN,12000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",NaN,tt0059243,en,The Great Race,"Professional daredevil and white-suited hero, ...",4.473327,...,7/1/65,160.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"The movie with 20,000-mile or one-million-laug...",The Great Race,"[{'id': 9253, 'name': 'slapstick'}, {'id': 159...","[{'cast_id': 1, 'character': 'Prof. Fate', 'cr...","[{'credit_id': '52fe445e9251416c75032581', 'de...",25333333
76,77,NaN,500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0242572,ta,Kandukondain Kandukondain,Two young women with differing views on love f...,0.660663,...,5/5/00,157.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kandukondain Kandukondain,NaN,"[{'cast_id': 1, 'character': 'Manohar', 'credi...","[{'credit_id': '52fe47c7c3a368484e0d8f41', 'de...",500000
97,98,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,tt1772980,ru,Mishen,"In the year 2020, a group of wealthy Moscovite...",1.042112,...,6/26/11,158.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Target,NaN,"[{'cast_id': 1001, 'character': 'Victor', 'cre...","[{'credit_id': '58cdbad4c3a36850e9011085', 'de...",73000
107,108,NaN,72000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0112573,en,Braveheart,"Enraged at the slaughter of Murron, his new br...",20.755149,...,5/24/95,177.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Every man dies. Not every man truly lives.,Braveheart,"[{'id': 30, 'name': 'individual'}, {'id': 388,...","[{'cast_id': 5, 'character': 'William Wallace'...","[{'credit_id': '52fe4225c3a36847f80079c1', 'de...",210000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2860,2861,NaN,22000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0083987,en,Gandhi,"In the early years of the 20th century, Mohand...",12.383755,...,11/30/82,191.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,His triumph changed the world forever.,Gandhi,"[{'id': 789, 'name': 'muslim'}, {'id': 958, 'n...","[{'cast_id': 7, 'character': 'Mahatma Gandhi',...","[{'credit_id': '574dc2c3925141120e0000cb', 'de...",77737889
2877,2878,NaN,18000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0086879,en,Amadeus,The incredible story of genius musician Wolfga...,12.677592,...,10/26/84,160.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,...Everything you've heard is true,Amadeus,"[{'id': 131, 'name': 'italy'}, {'id': 1233, 'n...","[{'cast_id': 4, 'character': 'Antonio Salieri'...","[{'credit_id': '57d19657c3a3684b9d008667', 'de...",51973029
2932,2933,NaN,12000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0060934,en,The Sand Pebbles,Engineer Jake Holman arrives aboard the gunboa...,11.354247,...,12/20/66,182.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,This is the heroic story of the men on the U.S...,The Sand Pebbles,"[{'id': 440, 'name': 'missionary'}, {'id': 478...","[{'cast_id': 1, 'character': 'Jake Holman', 'c...","[{'credit_id': '52fe442ec3a36847f8087029', 'de...",20000000
2944,2945,NaN,31500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...",http://www.apocalypsenow.com,tt0078788,en,Apocalypse Now,"At the height of the Vietnam war, Captain Benj...",13.596300,...,8/15/79,153.0,"[{'iso_639_1': 'km', 'name': ''}, {'iso_639_1'...",Released,This is the end...,Apocalypse Now,"[{'id': 1008, 'name': 'guerrilla'}, {'id': 126...","[{'cast_id': 29, 'character': 'Captain Benjami...","[{'credit_id': '52fe4210c3a36847f80012c7', 'de...",89460381
2965,2966,NaN,61000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",http://www.lesmiserablesfilm.com,tt1707386,en,Les Misérables,An adaptation of the successful stage musical ...,13.524080,...,12/18/12,157.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fight. Dream. Hope. Love.,Les Misérables,"[{'id': 254, 'name': 'france'}, {'id': 642, 'n...",NaN,NaN,441809770

### Question 7
Find movies with popularity greater than the average popularity.

In [ ]:
# Write your solution here
df.loc[df['popularity'] > df['popularity'].mean()]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
10,11,"[{'id': 1575, 'name': 'Rocky Collection', 'pos...",1000000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0075148,en,Rocky,"When world heavyweight boxing champion, Apollo...",14.774066,...,11/21/76,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His whole life was a million-to-one shot.,Rocky,"[{'id': 240, 'name': 'underdog'}, {'id': 276, ...","[{'cast_id': 16, 'character': 'Rocky Balboa', ...","[{'credit_id': '579948e9c3a36874e9007b0b', 'de...",117235147
11,12,"[{'id': 48190, 'name': 'Revenge of the Nerds C...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0093857,en,Revenge of the Nerds II: Nerds in Paradise,The members of the Lambda Lambda Lambda frater...,10.543750,...,7/10/87,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're Back!,Revenge of the Nerds II: Nerds in Paradise,"[{'id': 5801, 'name': 'nerd'}, {'id': 6876, 'n...","[{'cast_id': 2, 'character': 'Lewis Skolnick',...","[{'credit_id': '52fe46f49251416c750891e9', 'de...",22642033
12,13,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",20.726578,...,9/15/99,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Look closer.,American Beauty,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 6, 'character': 'Lester Burnham',...","[{'credit_id': '52fe420ec3a36847f80007c5', 'de...",356296601
13,14,"[{'id': 91698, 'name': 'Chili Palmer Collectio...",53000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0377471,en,Be Cool,"Disenchanted with the movie industry, Chili Pa...",13.314233,...,3/4/05,118.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone is looking for the next big hit,Be Cool,"[{'id': 3605, 'name': 'baseball bat'}, {'id': ...","[{'cast_id': 4, 'character': 'Chili Palmer', '...","[{'credit_id': '52fe43cbc3a36847f807039f', 'de...",95226116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993,2994,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,Viktor Navorski is a man without a country; hi...,14.092373,...,6/17/04,128.0,"[{'iso_639_1': 'bg', 'name': 'български език'}...",Released,Life is waiting.,The Terminal,"[{'id': 242, 'name': 'new york'}, {'id': 822, ...","[{'cast_id': 4, 'character': 'Viktor Navorski'...","[{'credit_id': '52fe4259c3a36847f8017699', 'de...",219417255
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

### Question 8
Find all movies having a vote_average greater than 8.

In [ ]:
# Write your solution here
m = df['popularity'].mean()
m

np.float64(8.463274199666666)

In [ ]:
df[df['popularity'] > m]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
10,11,"[{'id': 1575, 'name': 'Rocky Collection', 'pos...",1000000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0075148,en,Rocky,"When world heavyweight boxing champion, Apollo...",14.774066,...,11/21/76,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His whole life was a million-to-one shot.,Rocky,"[{'id': 240, 'name': 'underdog'}, {'id': 276, ...","[{'cast_id': 16, 'character': 'Rocky Balboa', ...","[{'credit_id': '579948e9c3a36874e9007b0b', 'de...",117235147
11,12,"[{'id': 48190, 'name': 'Revenge of the Nerds C...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0093857,en,Revenge of the Nerds II: Nerds in Paradise,The members of the Lambda Lambda Lambda frater...,10.543750,...,7/10/87,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're Back!,Revenge of the Nerds II: Nerds in Paradise,"[{'id': 5801, 'name': 'nerd'}, {'id': 6876, 'n...","[{'cast_id': 2, 'character': 'Lewis Skolnick',...","[{'credit_id': '52fe46f49251416c750891e9', 'de...",22642033
12,13,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",20.726578,...,9/15/99,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Look closer.,American Beauty,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 6, 'character': 'Lester Burnham',...","[{'credit_id': '52fe420ec3a36847f80007c5', 'de...",356296601
13,14,"[{'id': 91698, 'name': 'Chili Palmer Collectio...",53000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0377471,en,Be Cool,"Disenchanted with the movie industry, Chili Pa...",13.314233,...,3/4/05,118.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone is looking for the next big hit,Be Cool,"[{'id': 3605, 'name': 'baseball bat'}, {'id': ...","[{'cast_id': 4, 'character': 'Chili Palmer', '...","[{'credit_id': '52fe43cbc3a36847f807039f', 'de...",95226116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993,2994,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,Viktor Navorski is a man without a country; hi...,14.092373,...,6/17/04,128.0,"[{'iso_639_1': 'bg', 'name': 'български език'}...",Released,Life is waiting.,The Terminal,"[{'id': 242, 'name': 'new york'}, {'id': 822, ...","[{'cast_id': 4, 'character': 'Viktor Navorski'...","[{'credit_id': '52fe4259c3a36847f8017699', 'de...",219417255
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

### Question 1
Create a new column called half_runtime.

In [ ]:
# Write your solution here
df['half_runtime'] = df['runtime']/2
df['half_runtime']

0       46.5
1       56.5
2       52.5
3       61.0
4       59.0
        ...
2995    51.0
2996    51.0
2997    60.0
2998    45.0
2999    53.0
Name: half_runtime, Length: 3000, dtype: float64

### Question 2
Create a new column called double_runtime.

In [ ]:
# Write your solution here
df['double_runtime'] = df['runtime']*2
df['double_runtime']

0       186.0
1       226.0
2       210.0
3       244.0
4       236.0
        ...
2995    204.0
2996    204.0
2997    240.0
2998    180.0
2999    212.0
Name: double_runtime, Length: 3000, dtype: float64

### Question 3
Create a new column called profit = revenue - budget.

In [ ]:
# Write your solution here
df['profit'] = df['revenue'] - df['budget']
df['profit']

0        -1685349
1        55149435
2         9792000
3        14800000
4         3923970
          ...
2995      1596687
2996       180590
2997     24456761
2998    129963386
2999     47087155
Name: profit, Length: 3000, dtype: int64

### Question 4
Create a new column called profit_percentage.

In [ ]:
# Write your solution here
df['profit_percentage'] = df['profit']/df['budget'] * 100
df['profit_percentage']

0        -12.038207
1        137.873588
2        296.727273
3       1233.333333
4               inf
           ...
2995            inf
2996            inf
2997      37.625786
2998     309.436633
2999     134.534729
Name: profit_percentage, Length: 3000, dtype: float64

### Question 5
Create a column named budget_in_crores.

In [ ]:
# Write your solution here
df['budget_in_crores'] = df['budget'] / 100000000
df['budget_in_crores']

0       0.140
1       0.400
2       0.033
3       0.012
4       0.000
        ...
2995    0.000
2996    0.000
2997    0.650
2998    0.420
2999    0.350
Name: budget_in_crores, Length: 3000, dtype: float64

### Question 6
Create a column named runtime_hours.

In [ ]:
# Write your solution here
df['runtime_hour'] = df['runtime'] / 60
df['runtime_hour']

0       1.550000
1       1.883333
2       1.750000
3       2.033333
4       1.966667
          ...
2995    1.700000
2996    1.700000
2997    2.000000
2998    1.500000
2999    1.766667
Name: runtime_hour, Length: 3000, dtype: float64

### Question 1
Find the maximum profit.

In [ ]:
# Write your solution here
df['profit'].max()

1316249360

### Question 2
Find the minimum profit.

In [ ]:
# Write your solution here
df['profit'].min()

-107447384

### Question 3
Find the average profit.

In [ ]:
# Write your solution here
df['profit'].mean()

np.float64(44194517.77866667)

### Question 4
Find the median profit.

In [ ]:
# Write your solution here
df['profit'].median()

6121122.5

### Question 5
Find the mode of profit.

In [ ]:
# Write your solution here
df['profit'].mode()

0    0
Name: profit, dtype: int64

### Question 6
Find the total profit generated by all movies.

In [ ]:
# Write your solution here
df['profit'].sum()

np.int64(132583553336)

### Question 7
Find the maximum runtime.

In [ ]:
# Write your solution here
df['runtime'].max()

338.0

### Question 8
Find the minimum runtime.

In [ ]:
# Write your solution here
df['runtime'].min()

0.0

### Question 9
Find the average runtime.

In [ ]:
# Write your solution here
df['runtime'].mean()

np.float64(107.85657104736491)

### Question 10
Find the movie having the highest revenue.

In [ ]:
# Write your solution here
df.loc[df['revenue'] == df['revenue'].max()]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'id': 242, 'name': 'new york'}, {'id': 5539,...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,2.2,2.383333

### Question 11
Find the movie having the lowest budget.

In [ ]:
# Write your solution here
df.loc[df['budget'] == df['budget'].min()]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,236.0,3923970,inf,0.0,1.966667
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511,42.0,168.0,2586511,inf,0.0,1.400000
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391,50.0,200.0,34327391,inf,0.0,1.666667
11,12,"[{'id': 48190, 'name': 'Revenge of the Nerds C...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0093857,en,Revenge of the Nerds II: Nerds in Paradise,The members of the Lambda Lambda Lambda frater...,10.543750,...,"[{'id': 5801, 'name': 'nerd'}, {'id': 6876, 'n...","[{'cast_id': 2, 'character': 'Lewis Skolnick',...","[{'credit_id': '52fe46f49251416c750891e9', 'de...",22642033,49.0,196.0,22642033,inf,0.0,1.633333
17,18,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt1700845,en,The Invisible Woman,"In 1857, at the height of his fame and fortune...",4.183558,...,"[{'id': 5565, 'name': 'biography'}, {'id': 180...","[{'cast_id': 7, 'character': 'Charles Dickens'...","[{'credit_id': '53b94a260e0a2676c7009b37', 'de...",1234254,55.5,222.0,1234254,inf,0.0,1.850000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2989,2990,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,tt0206367,en,The Trumpet Of The Swan,The adventures of a young Trumpeter swan who c...,0.851599,...,"[{'id': 6653, 'name': 'trumpet'}, {'id': 10407...","[{'cast_id': 1, 'character': 'Father', 'credit...","[{'credit_id': '58bc9d609251416084044b0e', 'de...",100202,37.5,150.0,100202,inf,0.0,1.250000
2990,2991,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0118663,en,B.A.P.S.,Can two clueless Georgia homegirls with big he...,1.560980,...,"[{'id': 1437, 'name': 'burglar'}, {'id': 1946,...","[{'cast_id': 3, 'character': 'Nisi', 'credit_i...","[{'credit_id': '52fe477b9251416c7509af57', 'de...",7240837,45.0,180.0,7240837,inf,0.0,1.500000
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067,53.0,212.0,14715067,inf,0.0,1.766667
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,204.0,1596687,inf,0.0,1.700000
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,204.0,180590,inf,0.0,1.700000

### Question 1
List the top 10 movies by revenue.

In [ ]:
# Write your solution here
df.sort_values(by='revenue',ascending=False).head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'id': 242, 'name': 'new york'}, {'id': 5539,...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,2.20,2.383333
1761,1762,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,...,"[{'id': 830, 'name': 'car race'}, {'id': 3428,...","[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,68.5,274.0,1316249360,692.762821,1.90,2.283333
2770,2771,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,...,"[{'id': 8828, 'name': 'marvel comic'}, {'id': ...","[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694,70.5,282.0,1125403694,401.929891,2.80,2.350000
684,685,NaN,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,287.253654,...,"[{'id': 254, 'name': 'france'}, {'id': 2343, '...","[{'cast_id': 174, 'character': 'Belle', 'credi...","[{'credit_id': '551879bec3a3681f840004eb', 'de...",1262886337,64.5,258.0,1102886337,689.303961,1.60,2.150000
2322,2323,"[{'id': 8650, 'name': 'Transformers Collection...",195000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.transformersmovie.com/,tt1399103,en,Transformers: Dark of the Moon,Sam Witwicky takes his first tenuous steps int...,4.503505,...,"[{'id': 305, 'name': 'moon'}, {'id': 1612, 'na...","[{'cast_id': 3, 'character': 'Sam Witwicky', '...","[{'credit_id': '537f0b740e0a2624b40044d0', 'de...",1123746996,77.0,308.0,928746996,476.280511,1.95,2.566667
906,907,"[{'id': 263, 'name': 'The Dark Knight Collecti...",250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.thedarkknightrises.com/,tt1345836,en,The Dark Knight Rises,Following the death of District Attorney Harve...,20.582580,...,"[{'id': 849, 'name': 'dc comics'}, {'id': 853,...",NaN,NaN,1084939099,82.5,330.0,834939099,333.975640,2.50,2.750000
2135,2136,"[{'id': 295, 'name': 'Pirates of the Caribbean...",380000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://disney.go.com/pirates/index-on-stranger...,tt1298650,en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,27.887720,...,"[{'id': 658, 'name': 'sea'}, {'id': 1316, 'nam...","[{'cast_id': 15, 'character': 'Captain Jack Sp...","[{'credit_id': '566b4f54c3a3683f56005151', 'de...",1045713802,68.0,272.0,665713802,175.187843,3.80,2.266667
2562,2563,"[{'id': 137697, 'name': 'Finding Nemo Collecti...",200000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",http://movies.disney.com/finding-dory,tt2277860,en,Finding Dory,Dory is reunited with her friends Nemo and Mar...,14.477677,...,"[{'id': 1357, 'name': 'fish'}, {'id': 1453, 'n...","[{'cast_id': 2, 'character': 'Dory (voice)', '...","[{'credit_id': '55eb2fbb92514106d60041ab', 'de...",1028570889,48.5,194.0,828570889,414.285445,2.00,1.616667
881,882,"[{'id': 261307, 'name': 'Alice in Wonderland C...",200000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://disney.go.com/wonderland/,tt1014759,en,Alice in Wonderland,"Alice, an unpretentious and individual 19-year...",17.285093,...,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 7, 'character': 'Alice Kingsleigh...","[{'credit_id': '52fe44c09251416c7503fbc3', 'de...",1025491110,54.0,216.0,825491110,412.745555,2.00,1.800000
734,735,NaN,150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",http://movies.disney.com/zootopia,tt2948356,en,Zootopia,"Determined to prove herself, Officer Judy Hopp...",26.024868,...,"[{'id': 2527, 'name': 'fox'}, {'id': 10360, 'n...","[{'cast_id': 23, 'character': 'Judy Hopps (voi...","[{'credit_id': '536e09650e0a2647cb00fe6b', 'de...",1023784195,54.0,216.0,873784195,582.522797,1.50,1.800000

### Question 2
List the top 10 movies by profit.

In [ ]:
# Write your solution here
df.sort_values(by='profit',ascending=False).head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
1761,1762,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,...,"[{'id': 830, 'name': 'car race'}, {'id': 3428,...","[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,68.5,274.0,1316249360,692.762821,1.90,2.283333
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'id': 242, 'name': 'new york'}, {'id': 5539,...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,2.20,2.383333
2770,2771,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,...,"[{'id': 8828, 'name': 'marvel comic'}, {'id': ...","[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694,70.5,282.0,1125403694,401.929891,2.80,2.350000
684,685,NaN,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,287.253654,...,"[{'id': 254, 'name': 'france'}, {'id': 2343, '...","[{'cast_id': 174, 'character': 'Belle', 'credi...","[{'credit_id': '551879bec3a3681f840004eb', 'de...",1262886337,64.5,258.0,1102886337,689.303961,1.60,2.150000
2322,2323,"[{'id': 8650, 'name': 'Transformers Collection...",195000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.transformersmovie.com/,tt1399103,en,Transformers: Dark of the Moon,Sam Witwicky takes his first tenuous steps int...,4.503505,...,"[{'id': 305, 'name': 'moon'}, {'id': 1612, 'na...","[{'cast_id': 3, 'character': 'Sam Witwicky', '...","[{'credit_id': '537f0b740e0a2624b40044d0', 'de...",1123746996,77.0,308.0,928746996,476.280511,1.95,2.566667
734,735,NaN,150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",http://movies.disney.com/zootopia,tt2948356,en,Zootopia,"Determined to prove herself, Officer Judy Hopp...",26.024868,...,"[{'id': 2527, 'name': 'fox'}, {'id': 10360, 'n...","[{'cast_id': 23, 'character': 'Judy Hopps (voi...","[{'credit_id': '536e09650e0a2647cb00fe6b', 'de...",1023784195,54.0,216.0,873784195,582.522797,1.50,1.800000
1735,1736,"[{'id': 328, 'name': 'Jurassic Park Collection...",63000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",http://www.jurassicpark.com/,tt0107290,en,Jurassic Park,A wealthy entrepreneur secretly creates a them...,8.863776,...,"[{'id': 911, 'name': 'exotic island'}, {'id': ...","[{'cast_id': 4, 'character': 'Dr. Alan Grant',...","[{'credit_id': '52fe4238c3a36847f800d291', 'de...",920100000,63.5,254.0,857100000,1360.476190,0.63,2.116667
543,544,"[{'id': 119, 'name': 'The Lord of the Rings Co...",79000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.lordoftherings.net/,tt0167261,en,The Lord of the Rings: The Two Towers,Frodo and Sam are trekking to Mordor to destro...,29.423537,...,"[{'id': 603, 'name': 'elves'}, {'id': 606, 'na...","[{'cast_id': 13, 'character': 'Frodo Baggins',...","[{'credit_id': '52fe421ac3a36847f800454f', 'de...",926287400,89.5,358.0,847287400,1072.515696,0.79,2.983333
906,907,"[{'id': 263, 'name': 'The Dark Knight Collecti...",250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.thedarkknightrises.com/,tt1345836,en,The Dark Knight Rises,Following the death of District Attorney Harve...,20.582580,...,"[{'id': 849, 'name': 'dc comics'}, {'id': 853,...",NaN,NaN,1084939099,82.5,330.0,834939099,333.975640,2.50,2.750000
2562,2563,"[{'id': 137697, 'name': 'Finding Nemo Collecti...",200000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",http://movies.disney.com/finding-dory,tt2277860,en,Finding Dory,Dory is reunited with her friends Nemo and Mar...,14.477677,...,"[{'id': 1357, 'name': 'fish'}, {'id': 1453, 'n...","[{'cast_id': 2, 'character': 'Dory (voice)', '...","[{'credit_id': '55eb2fbb92514106d60041ab', 'de...",1028570889,48.5,194.0,828570889,414.285445,2.00,1.616667

### Question 3
List the top 10 movies by popularity.

In [ ]:
# Write your solution here
df.sort_values(by='popularity',ascending=False).head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
518,519,"[{'id': 468552, 'name': 'Wonder Woman Collecti...",149000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.warnerbros.com/wonder-woman,tt0451279,en,Wonder Woman,An Amazon princess comes to the world of Man t...,294.337037,...,"[{'id': 849, 'name': 'dc comics'}, {'id': 1701...",NaN,NaN,820580447,70.5,282.0,671580447,450.725132,1.49,2.350000
684,685,NaN,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,287.253654,...,"[{'id': 254, 'name': 'france'}, {'id': 2343, '...","[{'cast_id': 174, 'character': 'Belle', 'credi...","[{'credit_id': '551879bec3a3681f840004eb', 'de...",1262886337,64.5,258.0,1102886337,689.303961,1.60,2.150000
1695,1696,NaN,34000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt3890160,en,Baby Driver,After being coerced into working for a crime b...,228.032744,...,"[{'id': 642, 'name': 'robbery'}, {'id': 2076, ...","[{'cast_id': 9, 'character': 'Baby', 'credit_i...","[{'credit_id': '55c58c009251417a21000e5d', 'de...",224511319,56.5,226.0,190511319,560.327409,0.34,1.883333
2326,2327,"[{'id': 448150, 'name': 'Deadpool Collection',...",58000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.foxmovies.com/movies/deadpool,tt1431045,en,Deadpool,Deadpool tells the origin story of former Spec...,187.860492,...,"[{'id': 2095, 'name': 'anti hero'}, {'id': 307...","[{'cast_id': 99, 'character': 'Wade Wilson / D...","[{'credit_id': '57e564fac3a3681beb0000cc', 'de...",783112979,54.0,216.0,725112979,1250.194791,0.58,1.800000
2126,2127,"[{'id': 284433, 'name': 'Guardians of the Gala...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/221/guardians_o...,tt3896198,en,Guardians of the Galaxy Vol. 2,The Guardians must fight to keep their newfoun...,185.330992,...,"[{'id': 9663, 'name': 'sequel'}, {'id': 9715, ...","[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de...",863416141,68.5,274.0,663416141,331.708071,2.00,2.283333
1309,1310,NaN,61000000,"[{'id': 9648, 'name': 'Mystery'}, {'id': 53, '...",http://www.gonegirlmovie.com/,tt2267998,en,Gone Girl,With his wife's disappearance having become th...,154.801009,...,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 7, 'character': 'Nick Dunne', 'cr...","[{'credit_id': '52fe4d7fc3a368484e1ec741', 'de...",369330363,72.5,290.0,308330363,505.459611,0.61,2.416667
1715,1716,"[{'id': 173710, 'name': 'Planet of the Apes (R...",152000000,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",http://www.foxmovies.com/movies/war-for-the-pl...,tt3450958,en,War for the Planet of the Apes,Caesar and his apes are forced into a deadly c...,146.161786,...,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 6, 'character': 'Caesar', 'credit...","[{'credit_id': '591f036fc3a368774e036079', 'de...",369907963,70.0,280.0,217907963,143.360502,1.52,2.333333
1673,1674,"[{'id': 263, 'name': 'The Dark Knight Collecti...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,123.167259,...,"[{'id': 849, 'name': 'dc comics'}, {'id': 853,...","[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de...",1004558444,76.0,304.0,819558444,443.004564,1.85,2.533333
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'id': 242, 'name': 'new york'}, {'id': 5539,...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,2.20,2.383333
2293,2294,NaN,18000000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",http://wearethecircle.com/,tt4287320,en,The Circle,A young tech worker takes a job at a greedy In...,88.439243,...,"[{'id': 1576, 'name': 'technology'}, {'id': 58...","[{'cast_id': 14, 'character': 'Mae Holland', '...","[{'credit_id': '55528cd792514114c8000722', 'de...",20497844,55.0,220.0,2497844,13.876911,0.18,1.833333

### Question 4
Find the 10 longest movies.

In [ ]:
# Write your solution here
df.sort_values(by='runtime',ascending=False).head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
1211,1212,NaN,18000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt1321865,en,Carlos,"The story of Venezuelan revolutionary, Ilich R...",4.558075,...,"[{'id': 1419, 'name': 'gun'}, {'id': 7336, 'na...","[{'cast_id': 4, 'character': ""Ilich Ram√≠rez S...","[{'credit_id': '57352b61c3a3680253000870', 'de...",871279,169.0,676.0,-17128721,-95.159561,0.180000,5.633333
1922,1923,NaN,31115000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0056937,en,Cleopatra,Historical epic. The triumphs and tragedy of t...,8.591238,...,"[{'id': 5049, 'name': 'ancient rome'}, {'id': ...","[{'cast_id': 2, 'character': 'Cleopatra', 'cre...","[{'credit_id': '52fe4493c3a36847f809de91', 'de...",71000000,124.0,496.0,39885000,128.185762,0.311150,4.133333
523,524,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0049833,en,The Ten Commandments,"Escaping death, a Hebrew infant is raised in a...",11.147040,...,"[{'id': 1160, 'name': 'egypt'}, {'id': 2618, '...","[{'cast_id': 9, 'character': 'Moses', 'credit_...","[{'credit_id': '58acab8cc3a3686f0d00093f', 'de...",122700000,110.0,440.0,109700000,843.846154,0.130000,3.666667
1302,1303,NaN,44000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0080855,en,Heaven's Gate,Harvard graduate James Averill (Kris Kristoffe...,4.393576,...,"[{'id': 680, 'name': 'montana'}, {'id': 797, '...","[{'cast_id': 1, 'character': 'James Averill', ...","[{'credit_id': '52fe43d49251416c7501fcf7', 'de...",3484331,109.5,438.0,-40515669,-92.081066,0.440000,3.650000
1914,1915,NaN,56000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0279111,en,Gods and Generals,The film centers mostly around the personal an...,5.374563,...,"[{'id': 6091, 'name': 'war'}, {'id': 14643, 'n...","[{'cast_id': 3, 'character': 'Lt. Gen. Thomas ...","[{'credit_id': '52fe469e9251416c7507dfbb', 'de...",12923936,107.0,428.0,-43076064,-76.921543,0.560000,3.566667
2353,2354,NaN,8376800,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jodhaaakbar.com/,tt0449994,hi,Jodhaa Akbar,Jodhaa Akbar is a sixteenth century love story...,12.237488,...,"[{'id': 1157, 'name': 'wife husband relationsh...","[{'cast_id': 1, 'character': 'Jalaluddin Moham...","[{'credit_id': '52fe45c99251416c75062761', 'de...",13000000,106.5,426.0,4623200,55.190526,0.083768,3.550000
625,626,NaN,15000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0052618,en,Ben-Hur,Ben-Hur is a 1959 epic film directed by Willia...,14.319743,...,"[{'id': 3035, 'name': 'roman'}, {'id': 3071, '...","[{'cast_id': 20, 'character': 'Judah Ben-Hur',...","[{'credit_id': '52fe4266c3a36847f801b99f', 'de...",146900000,106.0,424.0,131900000,879.333333,0.150000,3.533333
1975,1976,NaN,2000000,"[{'id': 35, 'name': 'Comedy'}]",http://sh-sh.ru/,tt1651118,ru,Шапито-шоу,"Four parts and four travels to the sea, four c...",0.741560,...,"[{'id': 4344, 'name': 'musical'}]","[{'cast_id': 1001, 'character': '–æ—Ç–µ—Ü', 'c...","[{'credit_id': '52fe49f69251416c910bea51', 'de...",393816,103.5,414.0,-1606184,-80.309200,0.020000,3.450000
1731,1732,NaN,3900000,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,tt0222012,ta,Hey Ram,Saketh Ram's wife is raped and killed during d...,0.562097,...,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 1, 'character': 'Saket Ram', 'cre...","[{'credit_id': '52fe462cc3a368484e082aaf', 'de...",4900000,99.5,398.0,1000000,25.641026,0.039000,3.316667
2120,2121,NaN,12000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0054331,en,Spartacus,Spartacus is a 1960 American historical drama ...,11.110376,...,"[{'id': 1394, 'name': 'gladiator'}, {'id': 140...","[{'cast_id': 21, 'character': 'Spartacus', 'cr...","[{'credit_id': '52fe4294c3a36847f8029cc9', 'de...",60000000,98.5,394.0,48000000,400.000000,0.120000,3.283333

### Question 5
Find the 10 shortest movies.

In [ ]:
# Write your solution here
df.sort_values(by='runtime',ascending=True).head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
2865,2866,"[{'id': 188197, 'name': 'Cetto La Qualunque - ...",5579750,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2456720,it,Tutto tutto niente niente,NaN,2.208906,...,"[{'id': 8201, 'name': 'satire'}, {'id': 33501,...","[{'cast_id': 1, 'character': 'Cetto La Qualunq...","[{'credit_id': '52fe4c48c3a36847f82269b9', 'de...",8927600,0.0,0.0,3347850,60.000000,0.055797,0.0
1541,1542,NaN,750000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,tt3805180,ru,Все и сразу,NaN,0.201582,...,"[{'id': 642, 'name': 'robbery'}, {'id': 231149...","[{'cast_id': 3, 'character': 'Viktor', 'credit...","[{'credit_id': '53b7a7b90e0a2676b8006ab6', 'de...",3,0.0,0.0,-749997,-99.999600,0.007500,0.0
591,592,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt0768690,ru,А поутру они проснулись,NaN,0.402368,...,"[{'id': 4897, 'name': 'multiple character'}, {...","[{'cast_id': 8, 'character': '', 'credit_id': ...","[{'credit_id': '52fe4d449251416c911103f5', 'de...",234748,0.0,0.0,234748,inf,0.000000,0.0
390,391,NaN,6843500,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2550838,it,Il peggior Natale della mia vita,NaN,3.800073,...,NaN,"[{'cast_id': 2, 'character': 'Alberto', 'credi...","[{'credit_id': '52fe4bb79251416c7510bc79', 'de...",10703234,0.0,0.0,3859734,56.400000,0.068435,0.0
977,978,NaN,11000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2076251,it,La peggior settimana della mia vita,NaN,5.010563,...,NaN,"[{'cast_id': 4, 'character': 'Paolo', 'credit_...","[{'credit_id': '52fe4984c3a368484e12f923', 'de...",12935800,0.0,0.0,1935800,17.598182,0.110000,0.0
2498,2499,"[{'id': 106790, 'name': 'Hooked Collection', '...",3500000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",NaN,tt1620549,ru,Na Igre 2. Novyy Uroven,The continuation of the adventures of the hero...,0.884241,...,NaN,"[{'cast_id': 10, 'character': 'Vampire', 'cred...","[{'credit_id': '52fe46759251416c91055281', 'de...",2294357,0.0,0.0,-1205643,-34.446943,0.035000,0.0
2150,2151,NaN,5000000,"[{'id': 28, 'name': 'Action'}, {'id': 10749, '...",NaN,tt0477337,ru,Mechenosets,NaN,0.414793,...,NaN,"[{'cast_id': 2, 'character': 'Sasha', 'credit_...","[{'credit_id': '52fe46bec3a368484e0a14f7', 'de...",3919731,0.0,0.0,-1080269,-21.605380,0.050000,0.0
2785,2786,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 27, 'na...",NaN,tt0278675,fr,Revelation,"Since A.D. 50, a mysterious sacred artifact kn...",0.625099,...,NaN,"[{'cast_id': 1, 'character': 'Jake Martel', 'c...","[{'credit_id': '52fe4981c3a36847f819d97d', 'de...",10000000,0.0,0.0,10000000,inf,0.000000,0.0
1874,1875,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",http://www.vt4.be/vermist,tt1133617,en,Vermist,Five members of the Missing Persons Task Force...,0.229233,...,NaN,"[{'cast_id': 2, 'character': 'Murat Hoxha', 'c...","[{'credit_id': '52fe4838c3a36847f815cef1', 'de...",1,0.0,0.0,1,inf,0.000000,0.0
924,925,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2604346,es,¿Quién mató a Bambi?,It tells the story of two young friends who mu...,1.926826,...,"[{'id': 1930, 'name': 'kidnapping'}, {'id': 97...","[{'cast_id': 3, 'character': 'David', 'credit_...","[{'credit_id': '52fe4e31c3a368484e21370b', 'de...",850259,0.0,0.0,850259,inf,0.000000,0.0

### Question 6
Find the total number of movies available in each language.

In [ ]:
# Write your solution here
df['original_language'].value_counts()

original_language
en    2575
fr      78
ru      47
es      43
hi      42
ja      37
it      24
ko      20
cn      20
zh      19
de      18
ta      16
sv       8
pt       6
nl       6
fa       5
da       5
ro       4
hu       3
tr       3
no       2
te       2
pl       2
fi       2
ml       2
sr       1
cs       1
mr       1
ar       1
he       1
ur       1
el       1
vi       1
nb       1
bn       1
id       1
Name: count, dtype: int64

### Question 7
Find the language with the highest number of movies.

In [ ]:
# Write your solution here
df['original_language'].value_counts().head(1)

original_language
en    2575
Name: count, dtype: int64

### Question 8
Find the average runtime for each language.

In [ ]:
# Write your solution here
df.groupby('original_language')['runtime'].mean()

original_language
ar     98.000000
bn    125.000000
cn    105.450000
cs     90.000000
da    105.400000
de    122.294118
el     91.000000
en    106.984078
es    100.372093
fa     96.400000
fi    100.000000
fr    106.294872
he     90.000000
hi    148.880952
hu    126.000000
id    150.000000
it     91.625000
ja    112.972973
ko    115.100000
ml    137.000000
mr    162.000000
nb    103.000000
nl    107.333333
no     95.500000
pl     99.000000
pt    114.666667
ro    108.750000
ru     95.586957
sr     97.000000
sv    122.375000
ta    159.875000
te    146.000000
tr    119.000000
ur     94.000000
vi    135.000000
zh    121.368421
Name: runtime, dtype: float64

### Question 9
Find the average profit for each language.

In [ ]:
# Write your solution here
df.groupby('original_language')['profit'].mean()

original_language
ar    1.347747e+06
bn    5.363640e+05
cn    2.289881e+07
cs    1.739300e+04
da    8.557093e+06
de    1.641414e+07
el    7.849000e+06
en    4.931629e+07
es    6.874230e+06
fa    6.761852e+05
fi   -5.263340e+05
fr    9.643460e+06
he    9.125849e+06
hi    1.863042e+07
hu   -6.085407e+05
id   -1.872791e+06
it    1.286771e+07
ja    2.344045e+07
ko    9.347554e+06
ml    1.105000e+06
mr    2.900000e+06
nb    6.596780e+05
nl    1.066334e+06
no    6.110675e+05
pl    1.133119e+07
pt   -1.714683e+06
ro   -4.903502e+05
ru    3.869827e+06
sr   -4.998020e+05
sv    1.075551e+07
ta    9.987754e+06
te    6.642485e+06
tr    5.149674e+07
ur    5.019860e+05
vi   -6.610000e+05
zh    5.096795e+07
Name: profit, dtype: float64

### Question 1
Find the movie with the highest profit percentage.

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'half_runtime', 'double_runtime', 'profit', 'profit_percentage',
       'budget_in_crores', 'runtime_hour'],
      dtype='object')

In [ ]:
# Write your solution here
maxProfit = df['profit_percentage'].max()
highProfitPercentage = df[df['profit_percentage'] == maxProfit]
highProfitPercentage.loc[:,['original_title']]

                                  original_title
4                                           마린보이
7                                   Control Room
8                         Muppet Treasure Island
11    Revenge of the Nerds II: Nerds in Paradise
17                           The Invisible Woman
...                                          ...
2989                     The Trumpet Of The Swan
2990                                    B.A.P.S.
2994                                 School Ties
2995                                     Chasers
2996                                 Vi är bäst!

[812 rows x 1 columns]

### Question 2
Find movies that earned more than 5 times their budget.

In [ ]:
# Write your solution here
df[df['revenue']>5*df['budget']]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,244.0,14800000,1233.333333,0.012,2.033333
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,236.0,3923970,inf,0.000,1.966667
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075,46.0,184.0,71446075,510.329107,0.140,1.533333
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511,42.0,168.0,2586511,inf,0.000,1.400000
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391,50.0,200.0,34327391,inf,0.000,1.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2990,2991,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0118663,en,B.A.P.S.,Can two clueless Georgia homegirls with big he...,1.560980,...,"[{'id': 1437, 'name': 'burglar'}, {'id': 1946,...","[{'cast_id': 3, 'character': 'Nisi', 'credit_i...","[{'credit_id': '52fe477b9251416c7509af57', 'de...",7240837,45.0,180.0,7240837,inf,0.000,1.500000
2991,2992,"[{'id': 107469, 'name': 'Save The Last Dance C...",13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",NaN,tt0206275,en,Save the Last Dance,"A white midwestern girl moves to Chicago, wher...",4.794088,...,"[{'id': 4118, 'name': 'ballet dancer'}, {'id':...","[{'cast_id': 18, 'character': 'Sara Johnson', ...","[{'credit_id': '52fe4533c3a36847f80c1c6b', 'de...",91038276,56.0,224.0,78038276,600.294431,0.130,1.866667
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067,53.0,212.0,14715067,inf,0.000,1.766667
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,204.0,1596687,inf,0.000,1.700000
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,204.0,180590,inf,0.000,1.700000

### Question 3
Find movies that resulted in a loss.

In [ ]:
# Write your solution here
movieName = df['profit']<0
df[movieName]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,186.0,-1685349,-12.038207,0.14000,1.550000
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638,41.5,166.0,-4738362,-59.229525,0.08000,1.383333
15,16,NaN,500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://skinningmovie.com/synopsis.htm,tt1129437,sr,Šišanje,Novica is a mathematics champion in a Belgrade...,1.018477,...,"[{'id': 379, 'name': 'skinhead'}, {'id': 7492,...","[{'cast_id': 1001, 'character': 'Novica', 'cre...","[{'credit_id': '52fe4927c3a36847f818bb5f', 'de...",198,48.5,194.0,-499802,-99.960400,0.00500,1.616667
18,19,NaN,8000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt1487118,en,Chalet Girl,While working a job at an exclusive ski resort...,6.496259,...,"[{'id': 271, 'name': 'competition'}, {'id': 35...","[{'cast_id': 2, 'character': 'Kim Matthews', '...","[{'credit_id': '52fe495ac3a36847f8195d4d', 'de...",1749457,48.0,192.0,-6250543,-78.131788,0.08000,1.600000
27,28,NaN,11000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1486834,en,What If,"Wallace, a medical school dropout, has been re...",10.841891,...,"[{'id': 10556, 'name': 'male female relationsh...","[{'cast_id': 5, 'character': 'Wallace', 'credi...","[{'credit_id': '52fe4db4c3a368484e1f8003', 'de...",7847000,46.5,186.0,-3153000,-28.663636,0.11000,1.550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2977,2978,NaN,53000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://angeleyesmovie.warnerbros.com/index_nof...,tt0225071,en,Angel Eyes,A story about a seemingly unlikely couple who ...,5.396200,...,"[{'id': 9844, 'name': 'car crash'}, {'id': 150...","[{'cast_id': 1, 'character': 'Sharon Pogue', '...","[{'credit_id': '52fe4427c3a36847f8085447', 'de...",29700000,51.0,204.0,-23300000,-43.962264,0.53000,1.700000
2982,2983,NaN,500000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt2063781,en,Smashed,Kate and Charlie like to have a good time. The...,4.893812,...,NaN,"[{'cast_id': 1001, 'character': 'Kate Hannah',...","[{'credit_id': '557455c1c3a3686b7d003df7', 'de...",376597,42.5,170.0,-123403,-24.680600,0.00500,1.416667
2983,2984,NaN,35000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0118623,en,Anna Karenina,Anna (Marceau) is a wife and mother who has an...,5.660835,...,NaN,"[{'cast_id': 1, 'character': 'Anna Karenina', ...","[{'credit_id': '52fe47cac3a36847f81484f7', 'de...",791830,54.0,216.0,-34208170,-97.737629,0.35000,1.800000
2985,2986,NaN,37665000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",http://www.sonypictures.com/homevideo/freedoml...,tt0349467,en,Freedomland,A black police detective must solve a strange ...,5.388535,...,"[{'id': 577, 'name': 'black people'}, {'id': 5...","[{'cast_id': 13, 'character': 'Lorenzo Council...","[{'credit_id': '52fe4551c3a36847f80c76e7', 'de...",14655628,56.5,226.0,-23009372,-61.089531,0.37665,1.883333
2986,2987,NaN,20000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0338325,en,Paparazzi,A rising Hollywood actor decides to take perso...,12.553403,...,"[{'id': 10183, 'name': 'independent film'}]","[{'cast_id': 1, 'character': 'Bo Laramie', 'cr...","[{'credit_id': '5678044292514179dd008c37', 'de...",16605763,42.0,168.0,-3394237,-16.971185,0.20000,1.400000

### Question 4
Calculate the percentage of profitable movies.

In [ ]:
# Write your solution here
df[df['profit']>0].shape[0]/df.shape[0]*100

77.9

### Question 5
Calculate the percentage of loss-making movies.

In [ ]:
# Write your solution here
df[df['profit']<0].shape[0]/df.shape[0]*100

21.833333333333332

### Question 6
Find the top 5 most profitable Hindi movies.

In [ ]:
# Write your solution here
df[df['original_language'] == 'hi'].sort_values(by='profit', ascending=False).head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
585,586,NaN,10400000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt5074352,hi,दंगल,Dangal is an extraordinary true story based on...,8.792104,...,"[{'id': 5565, 'name': 'biography'}, {'id': 597...","[{'cast_id': 0, 'character': 'Mahavir Singh Ph...","[{'credit_id': '5714ef3f92514146c80003ea', 'de...",310000000,80.5,322.0,299600000,2880.769231,0.104,2.683333
2239,2240,"[{'id': 44976, 'name': 'Dhoom Series', 'poster...",19500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt1833673,hi,धूम ३,"To avenge his father's death, a circus enterta...",5.326716,...,"[{'id': 291, 'name': 'circus'}, {'id': 2492, '...","[{'cast_id': 2, 'character': 'Sahir', 'credit_...","[{'credit_id': '59488707c3a36816c504b523', 'de...",91000000,86.0,344.0,71500000,366.666667,0.195,2.866667
1572,1573,NaN,9100000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.rememberghajini.com/,tt1166100,hi,Ghajini,Sanjay a rich tycoon suffering from short term...,4.239080,...,"[{'id': 331, 'name': 'tattoo'}, {'id': 154785,...","[{'cast_id': 12, 'character': 'Sanjay Singhani...","[{'credit_id': '52fe45c99251416c75062659', 'de...",76000000,91.5,366.0,66900000,735.164835,0.091,3.050000
1656,1657,NaN,18000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",http://www.chennaiexp2013.com/chennaiexpress.aspx,tt2112124,hi,Chennai Express,Rahul embarks on a journey to a small town in ...,4.193560,...,"[{'id': 4412, 'name': 'grandfather'}, {'id': 4...","[{'cast_id': 2, 'character': 'Rahul Mithaiwala...","[{'credit_id': '581e56659251410f4f00f125', 'de...",62000000,70.5,282.0,44000000,244.444444,0.180,2.350000
1732,1733,"[{'id': 419784, 'name': 'Masti Collection', 'p...",5500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt2476154,hi,Grand Masti,"Amar, Prem and Meet are longtime friends who h...",1.250293,...,NaN,"[{'cast_id': 2, 'character': 'Amar', 'credit_i...","[{'credit_id': '52fe4db49251416c7513dd27', 'de...",47000000,70.0,280.0,41500000,754.545455,0.055,2.333333

### Question 7
Find the top 5 most profitable English movies.

In [ ]:
# Write your solution here
df[df['original_language'] == 'en'].sort_values(by='profit', ascending=False).head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
1761,1762,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,...,"[{'id': 830, 'name': 'car race'}, {'id': 3428,...","[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,68.5,274.0,1316249360,692.762821,1.90,2.283333
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'id': 242, 'name': 'new york'}, {'id': 5539,...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,2.20,2.383333
2770,2771,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,...,"[{'id': 8828, 'name': 'marvel comic'}, {'id': ...","[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694,70.5,282.0,1125403694,401.929891,2.80,2.350000
684,685,NaN,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,287.253654,...,"[{'id': 254, 'name': 'france'}, {'id': 2343, '...","[{'cast_id': 174, 'character': 'Belle', 'credi...","[{'credit_id': '551879bec3a3681f840004eb', 'de...",1262886337,64.5,258.0,1102886337,689.303961,1.60,2.150000
2322,2323,"[{'id': 8650, 'name': 'Transformers Collection...",195000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.transformersmovie.com/,tt1399103,en,Transformers: Dark of the Moon,Sam Witwicky takes his first tenuous steps int...,4.503505,...,"[{'id': 305, 'name': 'moon'}, {'id': 1612, 'na...","[{'cast_id': 3, 'character': 'Sam Witwicky', '...","[{'credit_id': '537f0b740e0a2624b40044d0', 'de...",1123746996,77.0,308.0,928746996,476.280511,1.95,2.566667

### Question 8
Find all movies with runtime between 120 and 180 minutes.

In [ ]:
# Write your solution here
df[(df['runtime'] > 120) & (df['runtime'] < 180)]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,244.0,14800000,1233.333333,0.012000,2.033333
12,13,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",20.726578,...,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 6, 'character': 'Lester Burnham',...","[{'credit_id': '52fe420ec3a36847f80007c5', 'de...",356296601,61.0,244.0,341296601,2275.310673,0.150000,2.033333
14,15,NaN,102000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0181689,en,Minority Report,John Anderton is a top 'Precrime' cop in the l...,20.666063,...,"[{'id': 476, 'name': 'self-fulfilling prophecy...","[{'cast_id': 5, 'character': 'Chief John Ander...","[{'credit_id': '52fe4223c3a36847f8006f3d', 'de...",358372926,72.5,290.0,256372926,251.346006,1.020000,2.416667
20,21,NaN,80000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,tt0120738,en,Lost in Space,The prospects for continuing life on Earth in ...,12.000579,...,"[{'id': 4379, 'name': 'time travel'}, {'id': 1...","[{'cast_id': 26, 'character': 'Dr. Zachary Smi...","[{'credit_id': '52fe433bc3a36847f80448b9', 'de...",136159423,65.0,260.0,56159423,70.199279,0.800000,2.166667
33,34,"[{'id': 207632, 'name': 'The ABCs of Death Col...",0,"[{'id': 27, 'name': 'Horror'}]",NaN,tt2926810,en,ABCs of Death 2,Taking all that was great from the first insta...,8.254856,...,"[{'id': 9706, 'name': 'anthology'}, {'id': 187...","[{'cast_id': 60, 'character': 'Assassin (Segme...","[{'credit_id': '52fe4cd69251416c91101d73', 'de...",7171,62.5,250.0,7171,inf,0.000000,2.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2969,2970,NaN,19800000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,tt0280707,en,Gosford Park,"Multiple storylined drama set in 1932, showing...",14.101101,...,"[{'id': 964, 'name': 'servant'}, {'id': 10594,...","[{'cast_id': 2, 'character': 'Mrs. Wilson', 'c...","[{'credit_id': '52fe4401c3a36847f807ceab', 'de...",87754044,68.5,274.0,67954044,343.202242,0.198000,2.283333
2970,2971,NaN,25000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",NaN,tt0103855,en,The Bodyguard,A former Secret Service agent grudgingly takes...,9.805017,...,"[{'id': 1156, 'name': 'sister sister relations...","[{'cast_id': 17, 'character': 'Rachel Marron',...","[{'credit_id': '52fe425ec3a36847f8019133', 'de...",411006740,64.5,258.0,386006740,1544.026960,0.250000,2.150000
2980,2981,NaN,300000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",https://www.facebook.com/Actionherobiju/,tt5320514,ml,ആക്ഷൻ ഹീറോ ബിജു,Biju is an honest policeman who fights the inj...,0.350207,...,"[{'id': 1252, 'name': 'suicide attempt'}, {'id...","[{'cast_id': 1, 'character': 'Sub-Inspector Bi...","[{'credit_id': '56b4d47f92514112b90045f6', 'de...",2500000,72.0,288.0,2200000,733.333333,0.003000,2.400000
2992,2993,NaN,1135654,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0015400,en,The Thief of Bagdad,A recalcitrant thief vies with a duplicitous M...,3.878515,...,"[{'id': 255, 'name': 'male nudity'}, {'id': 14...","[{'cast_id': 3, 'character': 'The Thief of Bag...","[{'credit_id': '52fe45bec3a368484e06c70b', 'de...",1213880,74.5,298.0,78226,6.888190,0.011357,2.483333
2993,2994,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,Viktor Navorski is a man without a country; hi...,14.092373,...,"[{'id': 242, 'name': 'new york'}, {'id': 822, ...","[{'cast_id': 4, 'character': 'Viktor Navorski'...","[{'credit_id': '52fe4259c3a36847f8017699', 'de...",219417255,64.0,256.0,159417255,265.695425,0.600000,2.133333

### Question 9
Find movies with revenue greater than 1 billion.

In [ ]:
# Write your solution here
df[df['revenue']>1000000000]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
684,685,NaN,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,287.253654,...,"[{'id': 254, 'name': 'france'}, {'id': 2343, '...","[{'cast_id': 174, 'character': 'Belle', 'credi...","[{'credit_id': '551879bec3a3681f840004eb', 'de...",1262886337,64.5,258.0,1102886337,689.303961,1.60,2.150000
734,735,NaN,150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",http://movies.disney.com/zootopia,tt2948356,en,Zootopia,"Determined to prove herself, Officer Judy Hopp...",26.024868,...,"[{'id': 2527, 'name': 'fox'}, {'id': 10360, 'n...","[{'cast_id': 23, 'character': 'Judy Hopps (voi...","[{'credit_id': '536e09650e0a2647cb00fe6b', 'de...",1023784195,54.0,216.0,873784195,582.522797,1.50,1.800000
881,882,"[{'id': 261307, 'name': 'Alice in Wonderland C...",200000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://disney.go.com/wonderland/,tt1014759,en,Alice in Wonderland,"Alice, an unpretentious and individual 19-year...",17.285093,...,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 7, 'character': 'Alice Kingsleigh...","[{'credit_id': '52fe44c09251416c7503fbc3', 'de...",1025491110,54.0,216.0,825491110,412.745555,2.00,1.800000
906,907,"[{'id': 263, 'name': 'The Dark Knight Collecti...",250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.thedarkknightrises.com/,tt1345836,en,The Dark Knight Rises,Following the death of District Attorney Harve...,20.582580,...,"[{'id': 849, 'name': 'dc comics'}, {'id': 853,...",NaN,NaN,1084939099,82.5,330.0,834939099,333.975640,2.50,2.750000
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'id': 242, 'name': 'new york'}, {'id': 5539,...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,2.20,2.383333
1673,1674,"[{'id': 263, 'name': 'The Dark Knight Collecti...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,123.167259,...,"[{'id': 849, 'name': 'dc comics'}, {'id': 853,...","[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de...",1004558444,76.0,304.0,819558444,443.004564,1.85,2.533333
1761,1762,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,...,"[{'id': 830, 'name': 'car race'}, {'id': 3428,...","[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,68.5,274.0,1316249360,692.762821,1.90,2.283333
2135,2136,"[{'id': 295, 'name': 'Pirates of the Caribbean...",380000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://disney.go.com/pirates/index-on-stranger...,tt1298650,en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,27.887720,...,"[{'id': 658, 'name': 'sea'}, {'id': 1316, 'nam...","[{'cast_id': 15, 'character': 'Captain Jack Sp...","[{'credit_id': '566b4f54c3a3683f56005151', 'de...",1045713802,68.0,272.0,665713802,175.187843,3.80,2.266667
2322,2323,"[{'id': 8650, 'name': 'Transformers Collection...",195000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.transformersmovie.com/,tt1399103,en,Transformers: Dark of the Moon,Sam Witwicky takes his first tenuous steps int...,4.503505,...,"[{'id': 305, 'name': 'moon'}, {'id': 1612, 'na...","[{'cast_id': 3, 'character': 'Sam Witwicky', '...","[{'credit_id': '537f0b740e0a2624b40044d0', 'de...",1123746996,77.0,308.0,928746996,476.280511,1.95,2.566667
2532,2533,"[{'id': 121938, 'name': 'The Hobbit Collection...",250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.thehobbit.com/,tt0903624,en,The Hobbit: An Unexpected Journey,"Bilbo Baggins, a hobbit enjoying his quiet lif...",23.253089,...,"[{'id': 483, 'name': 'riddle'}, {'id': 603, 'n...","[{'cast_id': 6, 'character': 'Gandalf', 'credi...","[{'credit_id': '52fe4783c3a36847f8139f7f', 'de...",1021103568,84.5,338.0,771103568,308.441427,2.50,2.816667
2562,2563,"[{'id': 137697, 'name': 'Finding Nemo Collecti...",200000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",http://movies.disney.com/finding-dory,tt2277860,en,Finding Dory,Dory is reunited with her friends Nemo and Mar...,14.477677,...,"[{'id': 1357, 'name': 'fish'}, {'id': 1453, 'n...","[{'cast_id': 2, 'character': 'Dory (voice)', '...","[{'credit_id': '55eb2fbb92514106d60041ab', 'de...",1028570889,48.5,194.0,828570889,414.285445,2.00,1.616667
2770,2771,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,...,"[{'id': 8828, 'name': 'marvel comic'}, {'id': ...","[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694,70.5,282.0,1125403694,401.929891,2.80,2.350000

### Question 10
Create a report showing Total Movies, Average Budget, Average Revenue, Average Profit, Maximum Profit, Minimum Profit.

In [ ]:
# Write your solution here
Total_Movies = df['original_title'].count()
Budget = df['budget'].mean()
Revenue = df['revenue'].mean()
Profit_Average = df['profit'].mean()
Max_Profit = df['profit'].max()
Min_Profit = df['profit'].min()

print('Total Movies:',Total_Movies)
print('Average Budget:',Budget)
print('Average Revenue:',Revenue)
print('Average Profit:',Profit_Average)
print('Maximum Profit:',Max_Profit)
print('Minimum Profit:',Min_Profit)

Total Movies: 3000
Average Budget: 22531334.11
Average Revenue: 66725851.88866667
Average Profit: 44194517.77866667
Maximum Profit: 1316249360
Minimum Profit: -107447384

### Question 11
Create a final summary dashboard using Pandas.

In [ ]:
# Write your solution here
pd.DataFrame(df.describe())

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:4779: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,id,budget,popularity,runtime,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hour
count,3000.000000,3.000000e+03,3000.000000,2998.000000,3.000000e+03,2998.000000,2998.000000,3.000000e+03,3000.000000,3000.000000,2998.000000
mean,1500.500000,2.253133e+07,8.463274,107.856571,6.672585e+07,53.928286,215.713142,4.419452e+07,inf,0.225313,1.797610
std,866.169729,3.702609e+07,12.104000,22.086434,1.375323e+08,11.043217,44.172869,1.123274e+08,NaN,0.370261,0.368107
min,1.000000,0.000000e+00,0.000001,0.000000,1.000000e+00,0.000000,0.000000,-1.074474e+08,-99.999948,0.000000,0.000000
25%,750.750000,0.000000e+00,4.018053,94.000000,2.379808e+06,47.000000,188.000000,1.795200e+04,17.176318,0.000000,1.566667
50%,1500.500000,8.000000e+06,7.374861,104.000000,1.680707e+07,52.000000,208.000000,6.121122e+06,239.984076,0.080000,1.733333
75%,2250.250000,2.900000e+07,10.890983,118.000000,6.891920e+07,59.000000,236.000000,4.143293e+07,NaN,0.290000,1.966667
max,3000.000000,3.800000e+08,294.337037,338.000000,1.519558e+09,169.000000,676.000000,1.316249e+09,inf,3.800000,5.633333