# Assignment: Pre-training, Fine-tuning, RLHF & Context Window

Answer all 15 questions.

## Question 1

**Differentiate Pre-training and Fine-tuning with examples.**

**Answer:**

Pre-training is the first stage, where a model is trained on a huge amount of general text data from the internet, books, articles, and so on. At this stage, it doesn't know anything about specific tasks, it just learns language patterns, grammar, facts, and general knowledge. This stage takes a lot of time, data, and compute.

Fine-tuning happens after pre-training, where the already trained model is trained further on a smaller, specific dataset to make it good at a particular task. Since the model already knows language in general, fine-tuning just teaches it to specialize.

Example:

A model like GPT is first pre-trained on massive text from the internet, so it learns general language understanding. Later, if a company wants to build a customer support chatbot, they fine-tune that same model on their own support tickets and conversations, so it learns to answer questions specific to their product.
So basically, pre-training builds general knowledge, and fine-tuning shapes that knowledge for a specific purpose.

## Question 2

**Explain self-supervised learning used in LLM pre-training.**

**Answer:**

Self-supervised learning means the model learns without needing manually labeled data, it creates its own labels from the text itself.
Part of the input is hidden or missing, and the model has to predict it using the rest of the text. Since the actual answer is already present in the original text, no human needs to label anything.

Example:

A sentence like "I love playing cricket" can be turned into a training example by hiding "cricket" and asking the model to predict it using the rest of the sentence. The original word becomes the label automatically.
This is what allows LLMs to be trained on massive amounts of raw internet text without needing manual labeling.

## Question 3

**Why is fine-tuning cheaper than pre-training?**

**Answer:**

Pre-training needs huge amounts of data and compute since the model is learning language from scratch. Fine-tuning starts with an already trained model, so it just needs a smaller dataset and less training time to adjust it for a specific task, making it way cheaper overall.

## Question 4

**Differentiate Instruction Tuning and Fine-tuning.**

**Answer:**

Fine-tuning means training an already pre-trained model further on a specific dataset for one particular task, like sentiment analysis or spam detection.
Instruction tuning is actually a type of fine-tuning, but more specific. Here the model is trained on instruction and response pairs, so it learns to follow different kinds of instructions properly, like "summarize this" or "translate this," instead of just completing text randomly.
Example: fine-tuning on movie reviews makes a model good at sentiment analysis only. Instruction tuning on many instruction-answer pairs makes a model good at following all kinds of prompts in general, which is what makes ChatGPT type models actually useful.

## Question 5

**What is RLHF? Explain all three stages.**

**Answer:**

RLHF stands for Reinforcement Learning from Human Feedback. It's a method used to make model outputs more aligned with what humans actually want, not just grammatically correct but genuinely helpful and safe.

Three stages:

* Supervised fine-tuning: The model is first fine-tuned on good quality human written responses to get a decent starting point.

* Reward model training: Humans rank multiple model outputs from best to worst, and this data trains a separate reward model that learns to score responses like a human would.

* Reinforcement learning: The main model is then further trained using this reward model as feedback, adjusting itself to produce responses that score higher, making it more helpful and aligned overall.

## Question 6

**Explain the role of human feedback in RLHF.**

**Answer:**

Human feedback is basically the whole foundation of RLHF, without it the model wouldn't know what a "good" response actually looks like from a human perspective. Instead of just learning to predict the next likely word, the model learns what humans actually prefer, find helpful, or consider safe.

Humans rank different responses generated by the model from best to worst, and this ranking data is used to train a reward model. That reward model then acts like a judge, guiding the main model during reinforcement learning to produce answers that align more with human expectations, tone, and values, rather than just being technically correct.

## Question 7

**What is a context window? Why is it important?**

**Answer:**

A context window is basically the amount of text, measured in tokens, that a model can look at or remember at one time while generating a response. Anything beyond that limit just gets cut off or ignored by the model.

It's important because it decides how much information the model can actually use to understand a conversation or a document. If the context window is small, the model might forget earlier parts of a long conversation or miss important details from a big document. A larger context window lets the model handle longer inputs, like entire articles or long chats, without losing track of what was said earlier.

## Question 8

**A model has an 8K context window. What does it mean?**

**Answer:**

It means the model can process up to 8,000 tokens at a time, this includes both the input you give it and the output it generates together. If the total conversation or text goes beyond 8,000 tokens, the earlier part gets pushed out or ignored since the model simply can't hold onto it anymore.

So basically, anything within that 8K limit, the model can remember and use as context, but anything before that gets forgotten, kind of like a memory limit for that particular conversation or document.

## Question 9

**Compare 8K, 32K and 128K context windows with use cases.**

**Answer:**

An 8K context window can handle around 6 pages of text at once. It's good enough for short conversations, quick questions and answers, or a simple chatbot reply where you don't need the model to remember too much.

A 32K context window can handle around 24 pages of text. This works better for longer conversations, analyzing a few documents together, or writing and reviewing code across multiple files, since it can hold a lot more information at once compared to 8K.

A 128K context window can handle around 96 or more pages of text. This is useful for really heavy tasks like feeding in an entire book, a huge codebase, or long research papers, since the model can understand everything together without needing to break the content into smaller chunks.

## Question 10

**Write Python code to load a pretrained Hugging Face model and perform inference.**

**Answer:**

In [1]:
!pip install transformers
from transformers import pipeline

classifier = pipeline('sentiment-analysis', model='distilbert-base-uncased-finetuned-sst-2-english')
result = classifier("I really enjoyed learning about transformers, it was so interesting.")
print(result)

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.12.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.20.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9997615218162537}]

In [2]:
result = classifier("I really enjoyed learning about transformers, it was so interesting.")
print(result)

[{'label': 'POSITIVE', 'score': 0.9997615218162537}]

## Question 11

**Write code to fine-tune a sentiment model on a custom dataset (outline acceptable).**

**Answer:**

In [3]:
!pip install transformers datasets

import pandas as pd
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

data = {
    'text': ["I love this product", "This was a waste of money", "Absolutely amazing experience", "Not good at all"],
    'label': [1, 0, 1, 0]
}
df = pd.DataFrame(data)
dataset = Dataset.from_pandas(df)

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(example):
    return tokenizer(example['text'], padding="max_length", truncation=True)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    logging_dir="./logs"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset
)

trainer.train()

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.12.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.20.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Map:   0%|          | 0/4 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=3, training_loss=0.6399898131688436, metrics={'train_runtime': 68.418, 'train_samples_per_second': 0.175, 'train_steps_per_second': 0.044, 'total_flos': 1589608783872.0, 'train_loss': 0.6399898131688436, 'epoch': 3.0})

## Question 12

**Debug: Why might an LLM forget earlier parts of a long conversation?**

**Answer:**

This happens because of the context window limit. Every model can only hold a fixed number of tokens at once, so once a conversation crosses that limit, the oldest messages get pushed out to make room for new ones.

LLMs also don't have real memory, they only see whatever text is included in the current request. Once earlier messages fall outside the window, they're basically invisible to the model.

To fix this, you can use a model with a bigger context window, summarize earlier parts of the conversation and feed that back in, or store important details externally and pull them in only when needed.

## Question 13

**Case Study: Choose a model for legal document analysis and justify using context window and fine-tuning.**

**Answer:**

**Case Study: Choosing a model for legal document analysis**

For legal documents, a large context window like 128K works best since legal files are long and every clause matters. Fine-tuning on legal datasets like contracts and case judgments helps the model understand legal terms properly, giving accurate results instead of generic ones.

## Question 14

**Calculate approximate token usage for a 25-page document and discuss whether a 16K context window is sufficient.**

**Answer:**

Token usage for a 25 page document

25 pages × around 750 tokens per page = around 18,750 tokens

Is 16K enough?
No, 16K (16,384 tokens) is barely below that, so the document would get cut off with no room left for the response. A 32K context window would be a safer and better choice here.

## Question 15

**Mini Project: Build a domain-specific chatbot using a pretrained model. Describe dataset, fine-tuning strategy, evaluation metrics, and deployment.**

**Answer:**

In [4]:
# Install libraries
!pip -q install transformers datasets sentencepiece accelerate

import pandas as pd
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    TrainingArguments,
    Trainer
)

In [5]:
# Create sample dataset
data = {
    "question": [
        "What is the last date for fee payment?",
        "When does the new semester start?",
        "How can I apply for a scholarship?",
        "Where can I collect my hall ticket?",
        "How do I check my exam results?",
        "Can I get a fee refund?",
        "How do I apply for a bonafide certificate?",
        "Where is the college library located?",
        "How can I contact the placement cell?",
        "How do I update my personal details?"
    ],
    "answer": [
        "The last date for fee payment is thirtieth July.",
        "The new semester starts on first August.",
        "You can apply for a scholarship through the student portal.",
        "Hall tickets can be collected from the examination office.",
        "Exam results are published on the student portal under Results.",
        "Fee refunds are processed within ten working days upon approval.",
        "You can apply for a bonafide certificate through the admin office.",
        "The library is located on the second floor of the main block.",
        "You can contact the placement cell through email or the campus office.",
        "You can update your details from the profile section of the student portal."
    ]
}
df = pd.DataFrame(data)
dataset = Dataset.from_pandas(df)
dataset

Dataset({
    features: ['question', 'answer'],
    num_rows: 10
})

In [6]:
# Load tokenizer and model
checkpoint = "google/flan-t5-small"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [7]:
# Preprocessing function
def preprocess(example):
    model_input = tokenizer(
        example["question"],
        max_length=64,
        truncation=True
    )
    labels = tokenizer(
        text_target=example["answer"],
        max_length=64,
        truncation=True
    )
    model_input["labels"] = labels["input_ids"]
    return model_input

tokenized_dataset = dataset.map(preprocess)

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

In [8]:
# Data collator
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

In [9]:
# Fine-tuning setup
training_args = TrainingArguments(
    output_dir="./college_chatbot",
    per_device_train_batch_size=2,
    num_train_epochs=20,
    learning_rate=2e-4,
    logging_steps=1,
    save_strategy="no",
    report_to="none"
)

In [10]:
# Train the model
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator
)
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=100, training_loss=0.5816352715343237, metrics={'train_runtime': 96.7873, 'train_samples_per_second': 2.066, 'train_steps_per_second': 1.033, 'total_flos': 749371097088.0, 'train_loss': 0.5816352715343237, 'epoch': 20.0})

In [11]:
# Save the model
model.save_pretrained("college_chatbot_model")
tokenizer.save_pretrained("college_chatbot_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('college_chatbot_model/tokenizer_config.json',
 'college_chatbot_model/tokenizer.json')

In [12]:
# Load saved model
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("college_chatbot_model")
model = AutoModelForSeq2SeqLM.from_pretrained("college_chatbot_model")

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

In [13]:
# Chat with bot
question = "When does the new semester start?"
inputs = tokenizer(question, return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=40)

print("User :", question)
print("Bot  :", tokenizer.decode(outputs[0], skip_special_tokens=True))

User : When does the new semester start?
Bot  : The new semester starts on first August.

In [14]:
question = "How do I get my hall ticket?"
inputs = tokenizer(question, return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=12)

print("User :", question)
print("Bot  :", tokenizer.decode(outputs[0], skip_special_tokens=True))

User : How do I get my hall ticket?
Bot  : Hall tickets can be obtained from the examination office.